### ISSUE TITLE
Starbase passively loses energy while having positive energy regeneration

### ISSUE THREAD

**Issue by imverybadatnames** [PavelZinchenko/event-horizon-frontier-builds#101]
https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164344125/39339c7c-40ff-4f39-924d-726772cd3e90

The starbase has 230 energy regen, but loses energy passively, i believe that the Scientist perks are not working on the starbase or some other different bugs.

**Comment by IsmollCheeKen** [comment]
I suspect the same thing is happening with my Harbour in my issues #81 and #78, it must be losing energy passively despite having positive energy regeneration - reason why it abruptly stops spawning drones and the braking system doesn't work. Could it be that the scientist energy upgrades aren't working for AI-controlled ships?
