### ISSUE TITLE
Scientist's energy consumption upgrade doesn't work for weapons

### ISSUE THREAD

**Issue by Pomeha-TLA** [PavelZinchenko/event-horizon-frontier-builds#116]
![Screenshot_20240405-125755_1](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/152905218/0fd98fba-0c8d-4148-b972-a049768e4589)
![Screenshot_20240405-125804](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/152905218/6bb500ff-0cb9-4f54-9fbf-07095905e1a7)

https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/152905218/054a6e03-7aa6-4024-8e66-69440f41633e

Energy should be enough right for 2 shots but its able to shoot only once

**Comment by PavelZinchenko** [comment]
#180
