### ISSUE TITLE
[баг] нет врагов 

### ISSUE THREAD

**Issue by MisterN13** [PavelZinchenko/event-horizon-frontier-builds#117]
Уже пятый раз не могу пройти уровень, в конце нет экрана победы (уровень220-2)

https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/161188319/dc70d472-3937-4e28-a034-ace462b04622

**Comment by PavelZinchenko** [comment]
Можете прислать свой сейв на help.eventhorizon@gmail.com? Уровни у всех различаются, у меня уровень 220-2 нормально проходится и на других уровнях тоже такой баг ни разу не случался

**Comment by MisterN13** [comment]
Баг пропал после перезагрузки приложения. Вообще он часто появляется на уровнях . Лечится перезапуском уровня или приложением .

**Comment by MisterN13** [comment]
Уровень этот я прошел
