### ISSUE TITLE
Better Way To Farm New Resources (is Missing?)

### ISSUE THREAD

**Issue by IsmollCheeKen** [PavelZinchenko/event-horizon-frontier-builds#127]
I looked back at this discussion thread (image below) because I suspected that there's something missing. We were promised to get harder enemies in exchange of a 'better way to farm the new resources', and so, we got the more difficult Class 3 enemies now, BUT it seems that the 'better way to farm the new resources' is missing.

![Screenshot_2024_0409_131147](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164343919/4b22dd0e-bd27-46fb-b806-61284047b48a)

**Comment by PavelZinchenko** [comment]
I have significantly increased the drop rate of research resources in exploration levels; the higher the level, the greater the resource yield. For instance, at level 1000, you can obtain about 100 resources from a single node.
