### ISSUE TITLE
Предложение по щиту

### ISSUE THREAD

**Issue by MisterN13** [PavelZinchenko/event-horizon-frontier-builds#13]
Нет смысла ИИ использовать энерго щит вручную. Ведь за активацию требуется много энергии, в то время как за поддержание энергии вообще не требуется.  Может стоит по умолчанию для ИИ сделать щит всегда включен? Иначе он в тупую расходует энергию включая его каждую секунду и толку от этого 0

Тем более пацаны хотят чтоб энерго щит работал как положено.

Или

Сделайте пожалуйста чтоб игрок управлял всеми настройками модулей корабля, а не ИИ

**Comment by PavelZinchenko** [comment]
Иногда есть смысл отключить щит. Когда нужно накопить энергии на выстрел, а корбль находится под аткой, включенный щит не дает ей восстановиться.
Я уже сдалал так чтобы ИИ не трогал модули которые настроены как автоматические.
