### ISSUE TITLE
[Enhancement] A Notice/Announcement Update for v2.9.4 & Scientist Mission Appearance

### ISSUE THREAD

**Issue by IsmollCheeKen** [PavelZinchenko/event-horizon-frontier-builds#133]
No. 1
Since +X module conversion will be coming to v2.9.5 (when it publicly releases), please consider updating v2.9.4 with a Notice/Announcement everytime players open the game, telling them about the conversion in the next update so they can prepare their +X modules and spend resources upgrading modules for the conversion.

If not, people could update while they are unprepared, causing them to lose out on potential resources upon conversion.

Consequences if a player is unprepared for the conversion:
• Weakened Fleet (from loss of +20 modules)
• Generally Harder Enemies
• Too Little Resources From Conversion

Levels in v2.9.4 is significantly easier compared to v2.9.5, players can easily blitz through the levels without much problems. The issue here is when they eventually update to v2.9.5, they can find themselves unable to progress since the enemies suddenly got harder + their whole fleet has been weakened + and they are already in Levels too deep to progress. Combine these with too little resources from conversion, then you are essentially stuck, unable to push forward.

No.2
Another issue is the Scientist NPC/Mission, I can guarantee that some players are not going to even know it exists, and if they do, they won't know how to get/unlock it, since the game tells absolutely nothing about it aside from the vague update logs in the Google Play Store. So, I propose a new way for the Mission to appear - make the Mission appear upon players passing Level 150, this guarantees that every player will see it instead of finding it by chance.

**Comment by GearGuardian91** [comment]
i agree with point no. 1, but point no.2...knowing it exists is one thing, but increasing the base level at which it appears? how about instead it be available from lvl 1-1 just like engineer? as harrowing as the grind is to just finish the mission itself, you will be at lvl 100+ before finishing it. im on week 3 and im at 331/500 total materials needed, only going up an average of about 7 per day. 

catfish merchant isnt common, mats in arena shop arent common or enough to really matter, and mats from investigation spots are rarer than finding santa store in explore.

**Comment by SuplexCity25284** [comment]
I've only been playing the new update a few days, and yeah, I'm on about 20 of some of the new scientist items, but it's definitely a grind.  I had to ask around Reddit at first to get what was going on.

I can definitely concur that the game is harder now.  I usually did well on normal levels, I'm on 140s, but survival levels sometimes kicked my butt, sometimes not.  Now I find I'm being wiped out 3 times a normal fight sometimes.  It's not fun.

**Comment by IsmollCheeKen** [comment]
Unfortunate
