### ISSUE TITLE
[request] яркость 

### ISSUE THREAD

**Issue by MisterN13** [PavelZinchenko/event-horizon-frontier-builds#134]
Можете яркость полоски 
 снизить ? Эти мерцание здоровья при уроне слишком режет глаза. 
Может стоит заменить на серый цвет? Еще можно сделать мерцание если здоровья упало ниже 30% Так же уберите мерцание  здоровья у врагов

**Comment by Thirteen0130** [comment]
Яркость надо понизить, согласен, просто немножко понизить, а цвет пусть будет таким же. Но мерцание здоровья у врагов надо оставить, чтобы знать, что урон вообще проходит по ним (Есть же резисты и фазовый сдвиг). Ниже 30% не надо. Пусть так и будет
