### ISSUE TITLE
Авто возврат 

### ISSUE THREAD

**Issue by MisterN13** [PavelZinchenko/event-horizon-frontier-builds#137]
Авто возврат корабля обратно к базе ,если ты далеко от неё.

Не срабатывает во время просмотра статистики боя
На арене только мешает.
Так как срабатывает при активации модулей или атаки.
Можете добавить настройку вкл/откл его?
Для меня он не то что бесполезен , он только мешает. Срабатывает когда не нужно и не срабатывает когда нужно.

**Comment by PavelZinchenko** [comment]
Убрал его
