### ISSUE TITLE
[баг]Расинхрон сборок 

### ISSUE THREAD

**Issue by MisterN13** [PavelZinchenko/event-horizon-frontier-builds#138]
На звёздной карте при выборе и редактирование корабля у меня такая картина:
![Screenshot_20240415_185750_Event Horizon - Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/161188319/89f9ae5e-df15-45bf-ba8d-c0324a11abdb)

Когда я захожу на уровень на том же корабле, уже другая картина в редакторе"
![Screenshot_20240415_185813_Event Horizon - Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/161188319/ae0d798e-f825-460f-ac43-08399ce9301f)

**Comment by PavelZinchenko** [comment]
Сборки кораблей на карте и в выбранном флоте могут отличаться. Редактирование корабля на экране карты никак не повлияет на корабль во флоте и наоборот. Если убрать корабль из флота, тогда его последняя сборка сохранися на карте.

**Comment by MisterN13** [comment]
Ок. Ну выглядит как баг , честно не очень понятно для чего это нужно.

**Comment by PavelZinchenko** [comment]
Не придумал как это лучше сделать. Допустим есть два флота с разными сборками. Какая должна быть на карте?

**Comment by MisterN13** [comment]
В моем понимании корабль который я редактирую (везде) должен меняться во всех сборках флотов . Что касается самих модулей на кораблях , есть отдельная система сохранений сборок (под корабль). Но это требует обсуждения с более опытными воинами, которые хотят не только разные корабли использовать пве и пвп но и сборки(для меня это лишнее, но кому-то понадобится)

Ответ на вопрос:
На текущем флоте сборка должна меняться и не важно на карте я редактирую или на уровне - это точно.

**Comment by MisterN13** [comment]
Новый игрок он точно не сможет понять почему он меняет модули на карте ,а в игре они не меняются
