### ISSUE TITLE
[Major Bug] Multiple Save State Issues

### ISSUE THREAD

**Issue by IsmollCheeKen** [PavelZinchenko/event-horizon-frontier-builds#140]
There appears to be a major issue with the game in saving information in the latest beta build. Ship builds are suddenly being rolled back to previous states, ship paintjobs being turned back into default, loss of items, loss of ship expansions, and even loss of mercenary pilots. And the resources, currency, and modules you spent/installed on these things aren't returned back to you. Please fix this as soon as possible.

**Comment by PavelZinchenko** [comment]
I believe I've fixed most of these bugs. If any remain, please provide further details.
