### ISSUE TITLE
Bring Back Old Ship Build Editing System

### ISSUE THREAD

**Issue by IsmollCheeKen** [PavelZinchenko/event-horizon-frontier-builds#145]
The latest release no longer allows the build editing of ships that isn't in the current fleet you are using. In order to change the build of a ship that isn't in your fleet, you have to include it into your fleet first/pilot it yourself, before you'll be able to edit it. This, in my opinion, was an unnecessary change, it only makes building multiple different ships tedious with the extra steps. Besides, you can already edit ship builds in your fleet via the fleet editor, so hiding extra/unused ships in the ships list of the build editor is unnecessary.

I know that the unused ships are hidden for organization sake, so I propose the solution of just simply putting the ships that are in use at the very top of the list.

**Comment by MisterN13** [comment]
In the latest update, you can remove modules from any ship on the star map

**Comment by IsmollCheeKen** [comment]
> In the latest update, you can remove modules from any ship on the star map

You can't (build 1865), the ship list on the build editor at the Starmap has been removed.

**Comment by TaipionsSalemClient** [comment]
uh that's bad, why though?

**Comment by PavelZinchenko** [comment]
In the latest build, opening an editor from the fleet window restricts you to selecting ships only from the fleet. However, if you open it from the star map, you can select any ship or starbase.

**Comment by IsmollCheeKen** [comment]
I just noticed that there is a new beta release (build 1866), and we can now change to different ships to edit at the starmap. Thank you.
