### ISSUE TITLE
[BUG] Infinite battle bug returns

### ISSUE THREAD

**Issue by GearGuardian91** [PavelZinchenko/event-horizon-frontier-builds#149]
this time the bug is continuous, i have tried beating 159-4 3x and ended the same way, like this, every time. but instead of returning to the base like last time, they just keep floating away. i found it happens after you click "all come here"

https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/163720452/a7e32346-e6a7-4df0-bda3-a70ad803850a

**Comment by PavelZinchenko** [comment]
Could you please attach you savegame file or send it to my email?

**Comment by PavelZinchenko** [comment]
I can't seem to find your email. Please make sure you sent it to help.eventhorizon@gmail.com

**Comment by PavelZinchenko** [comment]
I've tried level 159-4 dozens of times but was unable to reproduce the bug. Nevertheless, I've rewritten the enemy spawning code. I hope it helps.

**Comment by GearGuardian91** [comment]
> I've tried level 159-4 dozens of times but was unable to reproduce the bug. Nevertheless, I've rewritten the enemy spawning code. I hope it helps.

idk what could have caused it, i refreshed the game after posting the initial message, it happened on the first survival i tried (110) but never happened again. if it happens again, ill make a new issue. Thanks!

**Comment by GearGuardian91** [comment]
happened again, survival 111

https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/163720452/28f9ea23-ac5e-4d8f-8aa6-7e935b77440a

**Comment by PavelZinchenko** [comment]
Still unable to reproduce the issue. I've made additional changes that may fix it. Please let me know if you encounter it again in the latest build.
