### ISSUE TITLE
[Enhancement] Duel Series Improvements

### ISSUE THREAD

**Issue by IsmollCheeKen** [PavelZinchenko/event-horizon-frontier-builds#151]
The new Duel Series at the Arena is lacking a lot, the extremely slow paced battles makes it not worth doing compared to the Starbase Battle Series - and they just give the same rewards. It takes 4 business days to complete even one battle, that's an exaggeration but the point is given. You will often spend more time waiting for the next enemy ship to spawn than the time spent in battling it.

The Duel Series can be easily compared to how battles are done in EH:RPG, with the exception that it is lacking key features:
• Feature to change ship mid fight
• Battlefield looping around
• Feature to send in the next enemy ship/Feature to fight multiple enemy ships at once by the press of a button

**Comment by MisterN13** [comment]
Хотел бы добавить к посту. Нужно сделать возможность когда ставишь против своего флота, выбор кораблей - это первое.
Еще может стоит сделать сражения только между главными кораблями?
Я думал что оно так сразу и будет, ну типа 1x1

**Comment by PavelZinchenko** [comment]
I did everything but changing ships mid-fight. Changing ships is only permitted after defeating the enemy.
