### ISSUE TITLE
Arena bug

### ISSUE THREAD

**Issue by vlad-ultramarine** [PavelZinchenko/event-horizon-frontier-builds#152]
Захожу в режим арены, а там пусто
![Screenshot_20240419-184520](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/163786031/4f8ad63b-41b6-4d8a-a277-e61f99d42854)

**Comment by MisterN13** [comment]
Есть там все просто передвинуто

**Comment by vlad-ultramarine** [comment]
так мне должно сразу показывать, а не чтобы я сам искал

**Comment by vlad-ultramarine** [comment]
![Screenshot_20240419-222338](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/163786031/ba4cf4a7-87a6-4682-ad37-7751ca90d6e9)
