### ISSUE TITLE
[Major Bug] Loading Game Deletes Modules

### ISSUE THREAD

**Issue by IsmollCheeKen** [PavelZinchenko/event-horizon-frontier-builds#153]
The latest release (build 1871) removes modules from ships/storage every time you Load Game from Cloud. Someone could unknowingly Load Game, and then Save Game, making them lose modules permanently. Please fix this as soon as possible.

![Screenshot_20240420_122958](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164343919/ed9693ea-00c4-4b9b-b8c9-dfa7976ef5d3)
![Screenshot_20240420_123021](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164343919/fa001178-0b48-40e5-b2cc-c61cdcd12fc7)

**Comment by PavelZinchenko** [comment]
I fixed it in the latest release on GitHub, but it will take some time before the update is available on Google Play. However, it's not that severe; the modules aren't actually lost. They are just removed from ships and marked as "installed" in the inventory. Restarting the game will bring them back to the inventory.
