### ISSUE TITLE
[Bug] Resist

### ISSUE THREAD

**Issue by Thirteen0130** [PavelZinchenko/event-horizon-frontier-builds#159]
Так и было задумано?
![1713696106897](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164494313/5cd8eae3-0c28-4dac-89a2-56daf6c8e10e)

**Comment by MisterN13** [comment]
Если все три поставить, это особо тебя не спасёт

**Comment by Thirteen0130** [comment]
Знаю. Это работает со всеми тремя резистами и перком на массу

**Comment by vlad-ultramarine** [comment]
в два телефона удобно самому себе писать?

**Comment by PavelZinchenko** [comment]
Это не баг. Теперь можно установить несколько модификаций защиты и уменьшения массы корабля
