### ISSUE TITLE
[Enhancement] Ship Expansions

### ISSUE THREAD

**Issue by IsmollCheeKen** [PavelZinchenko/event-horizon-frontier-builds#164]
Suggestion to make ship expansions cost Credits to reset, have an undo feature, and when resetting expansions - it returns all Stars spent on it, the Credits spent on expanding will not be returned. To offset this enhancement, make the Credits cost twice as much (x2 Credits cost).

This will make it so that players will not have any wasted Stars on expansions, reduce expansion mistakes, and able to change ship expansion slots, at the general cost of credits, to suit their needs.

**Comment by PavelZinchenko** [comment]
I changed the price. Now it returns 90% of the stars you spent
