### ISSUE TITLE
[INQUIRY] EMP Nuke Nerf

### ISSUE THREAD

**Issue by GearGuardian91** [PavelZinchenko/event-horizon-frontier-builds#167]
When the EMP Nuke was first released, it did damage upon explosion, damage over time and killed energy. Now, it only does damage over time and kills energy. Why was this changed, and can the stats be made to reflect the new damage amounts? (if it isn't reverted)
below i have (1) a clip of how it used to work, (2) a clip of how it works now, and (3,4) the stats of the ship and (5) weapon used in (2). According to my math, there is no way my velez, let alone its shield, should have survived it with its current damage numbers.

(note: weapon in (1) is +40/+10 green mod of gold +200/+50 in (5))

(1) https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/163720452/099fa261-3280-49f1-b48c-0db3965d7203
(2) https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/163720452/305f76de-03f7-4c3a-9626-96a03ff50bed
(3) ![Screenshot_20240422-011858](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/163720452/c539ba4d-9f81-42e5-a69e-505c1bae5523)
(4) ![Screenshot_20240422-011845~2](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/163720452/15473870-648c-4657-8f6b-4199b7b420a0)
(5) ![Screenshot_20240422-013329](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/163720452/c087459b-1f0f-460c-8b3f-beb76938dfc9)

**Comment by PavelZinchenko** [comment]
It's probably a bug. I just reduced the base shield damage from 10k to 1k. I'll investigate

**Comment by GearGuardian91** [comment]
it being a bug didn't even cross my mind, even if it should have. Guess I need more sleep 😅
