### ISSUE TITLE
[REQUEST] option to disable double tap to hold button and set the button release delay

### ISSUE THREAD

**Issue by Neuron114** [PavelZinchenko/event-horizon-frontier-builds#169]
I've noticed a feature in build 1878 that when you double tap a button, it make the button hold automatically, which is really nice but I do wish there's an option to disable it in setting since it's interfere with my expectation of how long I want the button to be held. Also an option to set the button release delay since there's also a delay after you release a button

Thank you

**Comment by PavelZinchenko** [comment]
There is such option. If you go to the controls setup and select a button, you will see a "double tap to hold" checkbox.
