### ISSUE TITLE
[request] about mercenaries 

### ISSUE THREAD

**Issue by MisterN13** [PavelZinchenko/event-horizon-frontier-builds#171]
### Наемники в игре - это как коллекция для коллекционеров 
Очевидно их нужно более качественней проработать. Это все таки фишка игры. 
По этой причине, я предлагаю следующие изменения:

### Имена наемников
Сейчас имена не очень. Я встречаю работа у которого имя Екатерина Викторовна. Как то это не очень соответствует жёсткому роботу - убийце . 
Я помню как в старом добром "Diablo2" , встречались реально смешные имена. Типа - дикий доктор , потная швабра , и т.д .  Это всего лишь случайное сочетание слов, а как получалось смешно и прикольно.
Я предлагаю переработать имена на 3 расы.

Люди - тут можно оставить все как есть , имя и фамилия.

Пришельцы - вот тут можно использовать как в d2 и сочетать два разных слова из обычного словаря.

Роботы - думаю логичнее будет сделать цифровые имена. Ну тип 777 или 20024 , короче случайные цифры.

Ну это пока первое что приходит на ум.

### Разное поведение 
Я ставлю усилитель брони на ракетный корабль. По той причине , что мне не подходит то что он летает и обстреливает врага с далёка. Потому что у меня танк,  который должен идти на пролом . 
Вообще такие поведения было бы классно привязать к наёмнику и отвязать от модулей. Это сделало бы наёмников , еще более уникальными и редкими. Сами бои были бы намного разнообразнее. Боты использовали бы разные тактики с одинаковым орудиями.

Например вместе с перками добавлять еще одно поведение в бою из трёх.

Например 
Танк- то что есть если установить усилитель брони. 
Идет на таран, не уклоняется,  зажимает и некогда не отступает.

Clocking system:
- не включает его при столкновениях (исключения змей)

Сбалансированный
Держится на расстоянии стрельбы (всех своих орудий) используя маневры уклонения. 
Если закончится энергия не выходит из боя если он не под атакой

Трус - то что сейчас у ракетного корабля.
Держится на расстоянии самого дальнего орудия и обстреливает. Выходит из боя если закончится энергия и возвращается обратно с полным зарядом.
Если под атакой у него радиус атаки и скорости выше чем у врага , тогда отступает за радиус атаки врага(можно подключить форсаж) или вообще постоянно отступал за радиус атаки врага. По сути такую тактику использую я сам.

Clocking system:
- добавить задержку отключения 0.5 или 1 сек

**Comment by Thirteen0130** [comment]
Офигительная идея! Паша, действуй!

**Comment by PavelZinchenko** [comment]
Имена поменял, а более гибкую настройку поведения сделаю уже после релиза
