### ISSUE TITLE
[request] ai cloaking 

### ISSUE THREAD

**Issue by MisterN13** [PavelZinchenko/event-horizon-frontier-builds#173]
ИИ используют модуль при столкновении со своими или вражескими кораблями , вместо того чтоб уклонится от урона. Крайне не эффективно использовать заряд модуля для уклонения от столкновения. Также если установлен еще усилитель брони , ии выбирает усилитель брони - что тоже не эффективно.

**Comment by IsmollCheeKen** [comment]
The AI Cloaking to avoid a collision is more useful than you think, it prevents them getting stuck on other ships - most notable on ships that usually get stuck between Wormship/Jormungandr's tail segments.

**Comment by MisterN13** [comment]
> The AI Cloaking to avoid a collision is more useful than you think, it prevents them getting stuck on other ships - most notable on ships that usually get stuck between Wormship/Jormungandr's tail segments.

You can leave it selectively, for example, for a worm. But I think in other cases it's much more important to save the charge to dodge the lethal volley. In my practice, the AI often dies due to the fact that it used a collision charge when it could have dodged and stayed alive

**Comment by MisterN13** [comment]
Также хочу добавить что необходимо добавить задержку перед тем как выходить из прозрачности. Очень часто боты используя смертельный луч на несколько миллисекунд его отводят в сторону и потом обратно на врага , а заряд уже был сброшен . Если бы была задержка скажем 0.5 или 1  сек ,было бы норм

**Comment by MisterN13** [comment]
Если будите внедрять пост #171 
Можно добавить разное поведение с модулем, которое будет зависеть от тактики бота.
