### ISSUE TITLE
Имба и уровень сложности

### ISSUE THREAD

**Issue by MisterN13** [PavelZinchenko/event-horizon-frontier-builds#176]
Уровень 102 и вот так выглядят все мои боты:
![Screenshot_20240424_100338_Event Horizon - Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/161188319/23e7daf6-1914-4b03-93bc-9b3c2d4ffbfb)
![Screenshot_20240424_100441_Event Horizon - Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/161188319/e31da25c-2a34-4016-a041-dff4e2725cd5)

Как видите у них нет вообще брони и уровни проходятся особо не напрягаясь . Слишком легко и скучно.

Еще перк мусорщик просто имба какая-то. Я с ним прошел задание по открытию нового продавца, всего лишь за 10 минут. При том что я не чего не делал. Запустил выживание и все.

![Screenshot_20240424_153557_Event Horizon - Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/161188319/33c393ac-874d-4166-9679-9d6a521f7a64)

Ресурсов просто тьма 

Taking into account the fact that for a comfortable game, each player requires a different difficulty of the game. I suggest adding a different difficulty that can be changed in the settings.

**Comment by MisterN13** [comment]
Нужно сделать шанс выпадения предметов от перка 50 на 50% и повысить уровень сложности на уровня 50- 200

**Comment by magne00** [comment]
Levels 1-200 are supposed to be easy to entice newbies to keep playing the game.

Trust me, you don't want red ships to appear on your level.

**Comment by Zen9890** [comment]
> Levels 1-200 are supposed to be easy to entice newbies to keep playing the game.
> 
> Trust me, you don't want red ships to appear on your level.

I think this is far too much for earlygame lmao
something like taking difficulty up a notch past level 50 feels good enough and not overstretched

**Comment by Inedilarion** [comment]
> level 200 is already too hard enough for me

This problem, by the way, is due to the too rapid increase in the difficulty of the gameplay from too easy to requiring some skills in building ships, bases and fleets. A smoother increase in difficulty from first levels will just reduce this barrier

**Comment by Crdguy** [comment]
![image](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/30349278/a14ad5d8-e086-4399-bdbd-573dba0650bd)

**Comment by MisterN13** [comment]
> I have translated the message to english
> 
> mister, if you think early game are too easy, you might have forgotten the struggle of being in earlygame. No, do please do not make the game any harder, level 200 is already too hard enough for me that I can't even past that level until now. I'd suggest if you still want the game to be alot harder, make it optional instead of forcing players to get stress with it, it's not fun for some of us.

Why don't we compromise? Then everyone will be satisfied. For example, in the settings, make the difficulty selection point easy, medium, hard and impossible

**Comment by Zen9890** [comment]
> > I have translated the message to english
> > mister, if you think early game are too easy, you might have forgotten the struggle of being in earlygame. No, do please do not make the game any harder, level 200 is already too hard enough for me that I can't even past that level until now. I'd suggest if you still want the game to be alot harder, make it optional instead of forcing players to get stress with it, it's not fun for some of us.
> 
> Why don't we compromise? Then everyone will be satisfied. For example, in the settings, make the difficulty selection point easy, medium, hard and impossible

Difficulty options can make worse players actively feel bad for playing easy difficulty, so this solution isnt as good as you might think

**Comment by Neuron114** [comment]
> For example, in the settings, make the difficulty selection point easy, medium, hard and impossible

no, not easy, medium, or hard, those words will make player who plays on easy or medium feels noob than those who play at hard

"Base Difficulty" and "Enable Hardcore Enemy"
while also make "all come here" still optional thing for both difficulty

**Comment by Tree3324417** [comment]
we love elitism!!! we LOVE elitism!!!!!!!!!!!

**Comment by Tree3324417** [comment]
there is no damn point. this game is literally for 7+. go progress. lv200+ is there. if you want difficulty on lower, the only thing that im with is bringing back the old, specialized enemy waves.
