### ISSUE TITLE
[Bug] Drill Sergeant Not Replaced with Veteran

### ISSUE THREAD

**Issue by IsmollCheeKen** [PavelZinchenko/event-horizon-frontier-builds#181]
The latest patch notes mention the Drill Sergeant has been replaced with Veteran. It was not, instead Veteran acted as a new separate pilot perk
![Screenshot_20240427_003829](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164343919/06b66e66-7538-434c-92c3-472596675f1b)

**Comment by PavelZinchenko** [comment]
If any of your mercenaries had the drill sergeant perk, it has now been replaced with the veteran perk. However, the drill sergeant perk itself remains available in the game.
