### ISSUE TITLE
Unknown bugs keep appearing in bug detector 

### ISSUE THREAD

**Issue by Finront** [PavelZinchenko/event-horizon-frontier-builds#183]
In the  bug detector board unknown and some times unnoticed or irrelevant bugs appear. I think the dashboard is sensing things that are intended to happen or irrelevant and maybe failed conditions? I don't really know but it gets annoying really fast. And older issue made by   other player mentioned this. I just want to bring up the issue so it can hopefully get fix. I will upload pictures showing the bug detector 
![Screenshot_20240427-100024](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/162016473/220b1526-677f-4884-8fdb-ae1a8ef2bba6)

**Comment by PavelZinchenko** [comment]
This bug should be fixed already, are you using the latest build?

**Comment by Finront** [comment]
Thank you
