### ISSUE TITLE
[Request] +200% damage. Жалоба

### ISSUE THREAD

**Issue by Thirteen0130** [PavelZinchenko/event-horizon-frontier-builds#186]
"Removed the +200% damage and +50% cooldown mod for beams due to its unfair advantage"

Верните этот мод для большого синтез луча. Тартарус с единственным в игре вампир лучом был визитной карточкой. Он и так был до этого слабый, и мало кто его использовал. Так ещё и +200% урона убрали. Ну что же это такое?!
Раз на то дело пошло-удаляй нафиг Тартарус и этот вампир луч. ПОТОМУ ЧТО ОНИ СЛИШКОМ СИЛЬНЫЕ.(Сарказм)

**Comment by vlad-ultramarine** [comment]
реально нет (шутка)
![Screenshot_20240428-133818](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/163786031/4765a96e-d14c-4786-ab29-b3974b4a9158)

**Comment by vlad-ultramarine** [comment]
у лучей нет "нечестного преимущества", в поздней игре используют только ремонтые и тяжёлые ремонтные лучи, а в других сборках где можно использовать например тяжёлый лазер всегда ставят тяжелую разрядную пушку. Имело бы смысл тогда модификация +200% урона +50/+25 % к потреблению энергии

**Comment by Thirteen0130** [comment]
> у лучей нет "нечестного преимущества", в поздней игре используют только ремонтые и тяжёлые ремонтные лучи, а в других сборках где можно использовать например тяжёлый лазер всегда ставят тяжелую разрядную пушку. Имела бы смысл тогда модификация +200% урона +50/+25 % к потреблению энергии

Так я говорю про Тартарус вообще-то

**Comment by PavelZinchenko** [comment]
Лучше я просто увеличу урон оружия тартаруса. Урон + потребление энергии можно получить с помощью модулей. Для лучей эта модификация просто дает +200% урона, делая модификацию +100% бессмысленной. Для остального оружия она дает +100% учитывая увеличенное время перезарядки.

I'd better just increase the damage of the Tartarus weapon. Damage + energy consumption can be achieved using modules. For beams, this modification just gives +200% damage, making the +100% modification pointless. For other weapons, it gives +100%, considering the increased reload time.

**Comment by Thirteen0130** [comment]
> Лучше я просто увеличу урон оружия тартаруса. Урон + потребление энергии можно получить с помощью модулей. Для лучей эта модификация просто дает +200% урона, делая модификацию +100% бессмысленной. Для остального оружия она дает +100% учитывая увеличенное время перезарядки.
> 
> I'd better just increase the damage of the Tartarus weapon. Damage + energy consumption can be achieved using modules. For beams, this modification just gives +200% damage, making the +100% modification pointless. For other weapons, it gives +100%, considering the increased reload time.

Спасибо, что услышал нас!

**Comment by Inedilarion** [comment]
> Для лучей эта модификация просто дает +200% урона, делая модификацию +100% бессмысленной. Для остального оружия она дает +100% учитывая увеличенное время перезарядки.

Эта модификация делает бессмысленной модификацию на +100% урона для всего оружия, которое должно наносить урон (а также модификации на -50% времени перезарядки и -50% энергопотребления) . Это происходит из-за того, что затраты энергии на один снаряд остаются неизменными. И если у нас есть 10 энергии и пушка с 5 потребления и 5 урона, то за одну разрядку энергии с модификацией на +200% урона она нанесёт 30 урона, с модификацией +100% урона 20 урона, с модификацией -50% времени перезарядки 10 урона, при одинаковом уроне в секунду (а ещё модификация на +200% урона даёт больше энергоэффективности чем на -50% энергопотребления, ещё и урон усиливая, и это же касается модификации на +100% урона). Справедливости ради, для оружия с очень большим временем перезарядки (более 10 секунд) модификация на +200% урона может оказаться менее удобной чем другие упомянутые, но используются такие орудия довольно редко.
