### ISSUE TITLE
[Enhancement] +200 damage equivalents

### ISSUE THREAD

**Issue by nvcbl** [PavelZinchenko/event-horizon-frontier-builds#189]
Weapons shouldn't only have +200% something good, +50% something bad, so here's the suggested equivalents for other modules.

- +200% armor, +50% weight (all armor modules except reactive)
- +200% armor, +50% energy cost (reactive armor)
- +100% engine power, +50% energy cost (engines)
- +100% energy, +100% weight (reactors)

if these feel unbalanced feel free to step it down a bit

**Comment by Tree3324417** [comment]
Horribly unbalanced. Not just mentioning the extremely high size efficiency up, the downside dont make up for anything at all. 
Even the +200% damage +50% cooldown weapon modifier itself is unbalanced, but i will speak of that elsewhere.
