### ISSUE TITLE
New pilot perks, and the new pilot shop.

### ISSUE THREAD

**Issue by Tree3324417** [PavelZinchenko/event-horizon-frontier-builds#191]
- Doppelganger changes: Quoting some players from the game discord, the recent command point nerf to the doppelganger perk is considered outright lazy and variety-killing. Instead of this, i recommend making it nerf the stat buff by around 40%-50% on both attack and defense, combined with it taking a perk slot, should make it more of a situational perk.

- Hacker: We are still unsure of how this work, but some say it might be another step to ruining drones and clones entirely. Do it affect clones, and how do it affect enemy drones? Close proximity, or picked out of randomness?

- Veteran: I feels like the 20% to atk and def is quite lazily done. An idea in my head to replace this with is a buff that scales with time since battle start. Each minute, the pilot with veteran gains 5% extra atk and def, capped at 30% max on both stat. Of course this is just on my thought, others are welcome to give their take on this perk, or nothing could be done about it at all-which i dont think is a nice thing, through.

- Provocator: Some says that this might be balance breaking, but how do it work exactly? Do it just take all the enemy attention to the provocator ship, or do it 'select' or randomise?

- Berserker is quite....weird. Seriously, weird. I like the idea of friendly fire for extra attack, but some ships, especially those who uses easily controllable beams like heavy lightning might as well not care.

- The new arena shop is straight up unwelcome. This only encourages save scumming due to the massive cost and extra rng involved. Others are welcome to give solutions, but in my opinion it should be possible at least to 'question' the pilots with some credits or arena token, revealing speciality or one/two important traits in the process.

**Comment by Thirteen0130** [comment]
Изменения в двойниках мне не нравится. Чел, ты буквально говоришь убрать двойники и добавить такой же перк, как у специалиста. В чём смысл? Эти перки давно уже придуманы. Оставь в покое

**Comment by Tree3324417** [comment]
> Изменения в двойниках мне не нравится. Чел, ты буквально говоришь убрать двойники и добавить такой же перк, как у специалиста. В чём смысл? Эти перки давно уже придуманы. Оставь в покое

I am not saying to remove doppel nor touching specialist perk however? What i meant there is nerfing doppel itself not by increasing its CP, but decreasing power of the user ship? What do you mean here? Doppelganger wasnt invented a long time ago either. Or, is either your translator or mine going wrong?

**Comment by magne00** [comment]
> Изменения в двойниках мне не нравится. Чел, ты буквально говоришь убрать двойники и добавить такой же перк, как у специалиста. В чём смысл? Эти перки давно уже придуманы. Оставь в покое

Out of the 3 'rare' perks. Current Doppelganger has very little downsides to using;

-Berserker: has friendly fire.
-Hacker: if enemy has no drones/clones it's useless

Then Doppelganger: .... has cp x2 -1. The only downside is choosing what ships to use, which is obviously the strongest ships from each class. And you get extra 1cp from EACH doppelganger above frigate class.

**Comment by Thirteen0130** [comment]
> > Изменения в двойниках мне не нравится. Чел, ты буквально говоришь убрать двойники и добавить такой же перк, как у специалиста. В чём смысл? Эти перки давно уже придуманы. Оставь в покое
> 
> Однако я не говорю удалять доппеля или трогать перк специалиста? Что я имел в виду, что сам доппель нерфится не за счет увеличения его CP, а за счет уменьшения мощности корабля пользователя? Что вы здесь имеете в виду? Doppelganger тоже был изобретен не так давно. Или ваш переводчик или мой ошибаются?
> 
> После получения ответа от inedilarion, интерпретирующего ваш ответ как "приближающий доппеля к специалисту", я не понимаю, почему это может быть похоже. Специалист делает один корабль сильным, в то время как доппел допускает больше рассылки спама (особенно дронами, EMP, дальнобойщиками или с клонами, за счет худших характеристик%) Они не похожи, и применение также будет отличаться. И, по крайней мере, это лучше, чем уничтожать разнообразие кораблей, просто обманывая более мощные корабли, а затем даже получая бесплатную привилегию для фрегатов.

Похоже, из-за языкового барьера мы друг друга не понимаем, даже с переводчиками) Мне показалось, будто вы хотите заменить двойников на другой перк, увеличивающий % урона и защиты, что и делает специалист

**Comment by Tree3324417** [comment]
> > > Изменения в двойниках мне не нравится. Чел, ты буквально говоришь убрать двойники и добавить такой же перк, как у специалиста. В чём смысл? Эти перки давно уже придуманы. Оставь в покое
> > 
> > 
> > Однако я не говорю удалять доппеля или трогать перк специалиста? Что я имел в виду, что сам доппель нерфится не за счет увеличения его CP, а за счет уменьшения мощности корабля пользователя? Что вы здесь имеете в виду? Doppelganger тоже был изобретен не так давно. Или ваш переводчик или мой ошибаются?
> > После получения ответа от inedilarion, интерпретирующего ваш ответ как "приближающий доппеля к специалисту", я не понимаю, почему это может быть похоже. Специалист делает один корабль сильным, в то время как доппел допускает больше рассылки спама (особенно дронами, EMP, дальнобойщиками или с клонами, за счет худших характеристик%) Они не похожи, и применение также будет отличаться. И, по крайней мере, это лучше, чем уничтожать разнообразие кораблей, просто обманывая более мощные корабли, а затем даже получая бесплатную привилегию для фрегатов.
> 
> Похоже, из-за языкового барьера мы друг друга не понимаем, даже с переводчиками) Мне показалось, будто вы хотите заменить двойников на другой перк, увеличивающий % урона и защиты, что и делает специалист

ah, yeah, misunderstanding it is.

**Comment by PavelZinchenko** [comment]
> Hacker: We are still unsure of how this work, but some say it might be another step to ruining drones and clones entirely. Do it affect clones, and how do it affect enemy drones? Close proximity, or picked out of randomness?

Completely reworked, it now adds an additional drone to each drone bay.

> Veteran: I feels like the 20% to atk and def is quite lazily done. An idea in my head to replace this with is a buff that scales with time since battle start. Each minute, the pilot with veteran gains 5% extra atk and def, capped at 30% max on both stat. Of course this is just on my thought, others are welcome to give their take on this perk, or nothing could be done about it at all-which i dont think is a nice thing, through.

The Veteran is an experienced soldier. What drawbacks can he have? Perhaps -50% experience penalty for the ship.

> Provocator: Some says that this might be balance breaking, but how do it work exactly? Do it just take all the enemy attention to the provocator ship, or do it 'select' or randomise?

The Provocator perk makes the ship as a high-priority target, adding +100 points to the overall score. An additional 200 points are derived from the ship's distance, and the final 100 points are based on the total damage or repairing the ship has dealt since its last respawn.

> The new arena shop is straight up unwelcome. This only encourages save scumming due to the massive cost and extra rng involved. Others are welcome to give solutions, but in my opinion it should be possible at least to 'question' the pilots with some credits or arena token, revealing speciality or one/two important traits in the process.

The size class of the ship that the captain can use is now visible before purchase.
