### ISSUE TITLE
The heavy acid corroded torpedo gear panel won't open

### ISSUE THREAD

**Issue by qianyexiangling** [PavelZinchenko/event-horizon-frontier-builds#196]
The heavy acid corroded torpedo gear panel won't open.
The error message displayed in the game is“
❶[Exception] NullReferenceException:Object reference not set to an instance of an object.”

**Comment by qianyexiangling** [comment]
Hello, this bug occurred in version 2.9.5.1896




---Original---
From: ***@***.***&gt;
Date: Wed, May 1, 2024 17:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PavelZinchenko/event-horizon-frontier-builds] The heavy acidcorroded torpedo gear panel won't open (Issue #196)




 
Works fine for me. Are you using the latest beta?

**Comment by PavelZinchenko** [comment]
The latest Google Play beta version is 1898, in which this bug should be fixed
