### ISSUE TITLE
I can't play arena,no black bazzar just fighting bots

### ISSUE THREAD

**Issue by Absolutan115** [PavelZinchenko/event-horizon-frontier-builds#202]
![Screenshot_2024-05-05-19-03-31-587_com ZipasGames Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/142648525/13ef752b-aa7a-4a94-91e9-6ba511d2ac80)
![Screenshot_2024-05-05-19-03-35-155_com ZipasGames Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/142648525/5e1c6139-9ed5-4be1-a4a4-e1e67df05144)

Idk why

**Comment by PavelZinchenko** [comment]
It should work now. Please check

**Comment by Absolutan115** [comment]
Yes thanks Pavel,you very quick to react

**Comment by Absolutan115** [comment]
But new issue 
![Uploading Screenshot_2024-05-06-12-23-48-501_com.ZipasGames.Frontier.jpg…]()

**Comment by Absolutan115** [comment]
New issue 
![Screenshot_2024-05-06-12-23-48-501_com ZipasGames Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/142648525/a25cfb18-1de9-4261-949a-85e1cab75127)

**Comment by Absolutan115** [comment]
This
![Screenshot_2024-05-06-12-38-08-262_com ZipasGames Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/142648525/305d1559-31aa-4eee-b071-8ac9a80063d8)

**Comment by PavelZinchenko** [comment]
The server had problems (#206), but it's working now

**Comment by Absolutan115** [comment]
Ok thanks
