### ISSUE TITLE
Reseting Expansions

### ISSUE THREAD

**Issue by Lupuu0102** [PavelZinchenko/event-horizon-frontier-builds#203]
When I reset the expansion of any ship/starbase and gain the stars, if I close the game and reenter, the ship expansion don't resets, but I still get stars, and thats awfull, because players can abuse of that, and gain lots of stars.

**Comment by PavelZinchenko** [comment]
Are you sure about that? I've tested it multiple times and it appears that the expansions do reset each time.

**Comment by Lupuu0102** [comment]
https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/166023496/da9dff81-ab0f-4a92-9984-550a0dd0f88d

**Comment by PavelZinchenko** [comment]
Thanks! Fixed it.
