### ISSUE TITLE
not gaining player rating from duel series

### ISSUE THREAD

**Issue by imverybadatnames** [PavelZinchenko/event-horizon-frontier-builds#207]
after winning a match against a player with 100k defense rating, i didnt gain any rating
sorry for the low quality video, had to trim it to make it less than 10 mb

https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164344125/cf0802b0-b684-4c26-973e-09936be83e70

**Comment by PavelZinchenko** [comment]
Completed PvP levels with 5 consecutive wins no longer affect player rating. This is noted in the description.
