### ISSUE TITLE
Broken ship icons in builds editor

### ISSUE THREAD

**Issue by Inedilarion** [PavelZinchenko/event-horizon-frontier-builds#21]
![Screenshot_2024-02-27-22-30-13-126_com ZipasGames Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/66635560/07e091a1-a9f1-414c-ac3c-c92fe0c2e459)
![Screenshot_2024-02-27-22-30-21-608_com ZipasGames Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/66635560/b8ace27e-27dd-4edf-80bf-9c828bb298b3)
![Screenshot_2024-02-27-22-31-37-894_com ZipasGames Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/66635560/e379318c-582a-41f9-83ff-a4d4e96e83c4)

**Comment by PavelZinchenko** [comment]
Already fixed in the most recent build
