### ISSUE TITLE
[Request] Odin и Сложность игры 

### ISSUE THREAD

**Issue by Thirteen0130** [PavelZinchenko/event-horizon-frontier-builds#214]
В прохождении уровней очень часто появляются красные Odin с тяжёлыми ЭМИ бомбами. И если я говорю часто, то имею ввиду ОЧЕНЬ ЧАСТО. За уровень их может быть порядком от 40. Они отлетают далеко-далеко, где ИИ наёмников на них не обращает внимания, и стреляют ЭМИ бомбами. В результате, вся карта в проплешинах, наёмники ничего сделать не могут, тк энергии нет, и прохождение уровня, который можно пройти за 2 минуты, растягивается до 10 минут.

Решение: снизить частоту/количество одинаковых красных кораблей и добавить больше других разнообразных взаместо убранных.
Фото прилагается:
[
![Event Horizon - Frontier_2024-05-10-12-40-52](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164494313/24116ba7-8f22-49e4-be1c-0f6ce844ab4c)

**Comment by Bezbasheniy** [comment]
Поддерживаю, можно просто заменить их на других красныз титанов без этой противной особенности улетать в пердя. Илиже просто уменьшить им дальность чтобы не улетали за пределы досягаемости.

**Comment by vlad-ultramarine** [comment]
Так ии пользуется тем что его ракета может бить на такую дальность. Поэтому держится подальше

**Comment by Thirteen0130** [comment]
> Так ии пользуется тем что его ракета может бить на такую дальность. Поэтому держится подальше

Ок, ИИ умный, согласен. Но столько одинаковых кораблей... это вообще не очень...

**Comment by PavelZinchenko** [comment]
Odin doesn't use nuke anymore
