### ISSUE TITLE
Проблема с выбором флота

### ISSUE THREAD

**Issue by Bezbasheniy** [PavelZinchenko/event-horizon-frontier-builds#216]
![Screenshot_20240511-082752](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/169311403/52812baa-27b1-410c-b8f1-e5716b48ac76)
После последнего обновления невозможно изменить флот, ни создать команду, ни поменять текущую. При любой попытке выбивает данную ошибку.

**Comment by PavelZinchenko** [comment]
Можете прислать скрин с подробным описанием ошибки? Чтобы его получить, нужно нажать на сообщение.

**Comment by Bezbasheniy** [comment]
> Должно работать в последнем обновлении

Да заработало. Благодарю.
