### ISSUE TITLE
EMP nuke + afterburner = FTL drive

### ISSUE THREAD

**Issue by vlad-ultramarine** [PavelZinchenko/event-horizon-frontier-builds#217]
https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/163786031/91cc536d-0c69-404e-937a-3f71222708b9

Также похоже что у параметров ускорения нет ограничений, я смог сделать более 4000 углового ускорения на whistle и ии уже трудно им управлять. Считаю что лимит скорости должен быть 30/30 или 40/40 и ускорение тоже должно быть ограничено

**Comment by PavelZinchenko** [comment]
Убавил лимит скорости до 30/30. и ускорения до 300/300
