### ISSUE TITLE
[Enhancement] Arena rank upgrade and additional feature requests

### ISSUE THREAD

**Issue by NerdyQT** [PavelZinchenko/event-horizon-frontier-builds#22]
- Increase or remove the cap of Arena's ranking from 20000, so that there is a better reflection in strength for opponents, and also more tokens awarded instead of capping at 21 tokens. As of now, most new players and endgame players are clumped up around 19k-20k rank.
- Add an unique arena invitation code for each player so it can be shared for testing builds and strength between players
- Add an option to save a defense fleet for arena only. Other players will fight this fleet instead of the current fleet the defender is using.

**Comment by PavelZinchenko** [comment]
1.  Cap increased to 100000, also updated the rating calculation system to improve player distribution by rating in the future.
2. Invitation codes implemented
3. Working on it

**Comment by TaipionsSalemClient** [comment]
The current rating calculations may not be optimal, yet

Losing at high levels will lose you 2k rating or so I heard, whereas winning a fight only gives a few points each.

Issue: previous 20k ratings were apparently just multiplied with 5x => the 90k to 100k range is FILLED TO THE TOP with old, outdated and inactive fleets, weak fleets.
Players that are inactive should be reduced in rank or removed from the arena fleet list.

**Comment by PavelZinchenko** [comment]
> Losing at high levels will lose you 2k rating or so I heard, whereas winning a fight only gives a few points each.

It was a bug and it's fixed

> Players that are inactive should be reduced in rank or removed from the arena fleet list.

The new database currently contains only 800 players, which is insufficient. I need to get opponents from the old DB, which has 500k players. Once the new DB accumulates more players after the release, I will completely disable the old one
