### ISSUE TITLE
Wormships getting stuck in the starbases(except Research Station)

### ISSUE THREAD

**Issue by Lupuu0102** [PavelZinchenko/event-horizon-frontier-builds#221]
Please, fix that, it's really annoying.

![Screenshot_2024-05-08-22-12-38-51_48c014f8726d52b765b87002fd126ed8.jpg](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/166023496/9b9ecc70-6951-4991-af87-3308c8f9214a)

**Comment by Thirteen0130** [comment]
Это вечная проблема, которую разработчик почему-то игнорирует

**Comment by Inedilarion** [comment]
Это можно довольно просто решить сделав хвост прозрачным для союзников, как в случае с дронами (союзные корабли, кстати, в хвосте активно застряют)

**Comment by Thirteen0130** [comment]
> Это можно довольно просто решить сделав хвост прозрачным для союзников, как в случае с дронами (союзные корабли, кстати, в хвосте активно застряют)

Да! Это решило бы все проблемы! Полностью согласен! Столько багов есть из-за этого хвоста, прям ужас. Только надо сделать, чтобы для самого червя хвост не был прозрачным, а то можно будет лететь сквозь него

**Comment by Lupuu0102** [comment]
> Это можно довольно просто решить сделав хвост прозрачным для союзников, как в случае с дронами (союзные корабли, кстати, в хвосте активно застряют)

That's the solution.

**Comment by PavelZinchenko** [comment]
Made minor changes to tail behavior. Worms should no longer get stuck... at least for long

**Comment by Lupuu0102** [comment]
> Made minor changes to tail behavior. Worms should no longer get stuck... at least for long

Thanks.
