### ISSUE TITLE
[Request] Afterburner

### ISSUE THREAD

**Issue by Thirteen0130** [PavelZinchenko/event-horizon-frontier-builds#227]
"Система форсажа увеличивает скорость и ускорение на 200%, потребляя 30% от общего энергопотребления всех двигателей в секунду."
  Влияет ли -x% энергопотребления модуля на эти 30%? Если нет, то исправьте, пожалуйса

"The afterburner system increases speed and acceleration by 200%, consuming 30% of the total energy consumption of all engines per second."
   Does -x% of the module's energy consumption affect these 30%? If not, please fix it.

**Comment by PavelZinchenko** [comment]
Fixed
