### ISSUE TITLE
[Enhancement] QOL feature from a few versions back

### ISSUE THREAD

**Issue by nvcbl** [PavelZinchenko/event-horizon-frontier-builds#232]
So a few versions ago, before the UI was the current one, you could drag items out from the item info panel you get when you tap on a module, and now that's gone. If you're still open to add minor features, could you please add this back?

**Comment by PavelZinchenko** [comment]
I'm not sure what you mean. In the ship editor, you can drag items from the item panel. Could you explain further?

**Comment by nvcbl** [comment]
What i mean is that you should be able to drag items out from the module settings panel, the one that lets you set what button a module is triggered by, just like from a few versions ago (back before the UI was changed to the current one)

**Comment by PavelZinchenko** [comment]
Still don't get it. Are you referring to this panel? It's possible to drag items from there.
![image](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/27402398/ee2d79b6-f2df-4ac5-8a89-6a8881b65ca8)

**Comment by nvcbl** [comment]
The panel that i am referring to is the one you get when you tap on a module already installed on a ship, so if you tap on the gravitsappa on that build, that's the panel that i am talking about.
