### ISSUE TITLE
[Request]buy mercenaries with rare perk at black bazaar

### ISSUE THREAD

**Issue by CNY23662-22** [PavelZinchenko/event-horizon-frontier-builds#234]
Some new mercenary perks very hard to obtain(like"doppelganger"or "robotnik" ) ,could you just sell mercenaries with them at black bazaar or add some mercenary shop in investigate mission.

**Comment by Snowgods** [comment]
They already  are...  You have to buy the before you know what they are though.

**Comment by CNY23662-22** [comment]
I am sorry.I didn't play duel before and I don't know the outlaws haven already have.
