### ISSUE TITLE
Невозможность поставить на автоогонь редко стреляющее оружие / Inability to set weapon with big cooldown to auto fire

### ISSUE THREAD

**Issue by Inedilarion** [PavelZinchenko/event-horizon-frontier-builds#236]
При времени перезарядки более 1 секунды, с учётом бонуса от модулей авто-перезарядки, оружие не выходит поставить на автоогонь. Это не касается заряжаемого оружия

If the reload time is more than 1 second, taking into account the bonus from auto-reload modules, the weapon cannot be set to automatic fire. This does not apply to charging weapons.

https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/66635560/d1b6a821-2f62-4431-939b-6012c362a4a6

**Comment by PavelZinchenko** [comment]
This is intentional. Do you really need to set a weapon with such a slow fire rate to autofire?

**Comment by Inedilarion** [comment]
Certainly. Many builds with rarely firing weapons adjust the weapon reload time to the energy recharge time for continuous fire. In the video, my ship is for research and it would be very useful to be able to continuously fire a torpedo to constantly clear out all the enemies around

**Comment by PavelZinchenko** [comment]
Increased time limit to 2 sec

**Comment by Inedilarion** [comment]
> Increased time limit to 2 sec

2 seconds is not enough. Please remove this limit, it doesn't have any sense.
