### ISSUE TITLE
Сломанные расширения корабля после добавления новых клеток / Broken ship extensions after adding new cells

### ISSUE THREAD

**Issue by Inedilarion** [PavelZinchenko/event-horizon-frontier-builds#237]
Было/стало. Сборка немного другая, но расширения были теми же что на первом скриншоте. Учитывая возвращение звёзд при сбросе расширений, это не настолько критично как было бы раньше, но всё равно лучше бы подобного избежать в релизной версии игры (или сбросить расширения и выдать компенсацию). С Оверлордом такой проблемы не возникло.

It was/has become. The build is slightly different, but the extensions were the same as in the first screenshot. Considering the return of stars when resetting expansions, this is not as critical as it would be before, but it would still be better to avoid this in the release version of the game (or reset the extensions with compensation). There was no such problem with Overlord.

![Screenshot_2018-12-14-10-37-40-345_com ZipasGames Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/66635560/9b7e8101-29f3-49d1-be79-5f6bb0d34449)
![Screenshot_2024-05-15-15-01-59-895_com ZipasGames Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/66635560/b3f62085-85a6-42b2-a7a3-8d16d46f2fc4)

**Comment by PavelZinchenko** [comment]
This issue should only occur when upgrading from an earlier beta version. Loading a save from version 2.9.4 should not break the extensions.
