### ISSUE TITLE
[Enhancement] bot inertia stabilizers

### ISSUE THREAD

**Issue by Thirteen0130** [PavelZinchenko/event-horizon-frontier-builds#238]
Как насчёт добавить для игроков ботовский стабилизатор инерции? (Тот что большой, на много клеток, синенький такой). В игру уже было добавлено множество ботовский модулей для игроков (анигиляционный луч, ремлучи, ионные пушки и тд), даже были введены крутые двигатели. А вот стабилизаторы и компенсаторы в игре не менялись, наверное, с самого первого запуска. Например, обидно, когда на корабле стоят крутые двигатели, а корабль медленный, так как масса огромнейшая, а места для компенсаторов больше нет, вообще. (Если сомневаетесь вводить ли в игру ботовский стабилизатор, то можно сделать больше потребление энергии для баланса, как было с  движками на антиматерии)

How about adding a bot inertia stabilizer for the players? (The one that is big, with many cells, is so blue). A lot of bot modules for players have already been added to the game (anihilation beam, remlocks, ion cannons, etc.), cool engines have even been introduced. But the stabilizers and compensators in the game have not changed, probably, since the very first launch. For example, it's a shame when there are cool engines on the ship, and the ship is slow, since the mass is huge, and there is no place for compensators anymore, at all. (If you are in doubt whether to introduce a bot stabilizer into the game, then you can make more energy consumption for balance, as was the case with antimatter engines)

**Comment by vlad-ultramarine** [comment]
They called inertia nullifiers. And idk, well it's on Pavel's decision

**Comment by Thirteen0130** [comment]
> Они назвали нейтрализаторы инерции. И, idk, ну, это решение Павла

Надеюсь, он всё же их добавит)
I hope he will add them anyway)

**Comment by PavelZinchenko** [comment]
They are too powerful. Inertial dampers reduce mass by 300 per cell, inertial stabilizers by 375 per cell, and inertial nullifiers by 857 per cell. If I make them less effective, I'll have to rebuild many ship designs that use them.

Instead, I can make a new version with lower characteristics for players, while keeping the nullifiers available only for enemies.

**Comment by Thirteen0130** [comment]
> Они слишком мощные. Инерционные амортизаторы уменьшают массу на 300 единиц на ячейку, инерционные стабилизаторы на 375 единиц на ячейку и инерционные нейтрализаторы на 857 единиц на ячейку. Если я сделаю их менее эффективными, мне придется перестроить многие конструкции кораблей, в которых они используются.
> 
> Вместо этого я могу создать новую версию с более низкими характеристиками для игроков, оставив нейтрализаторы доступными только для врагов.


Поэтому я предлагаю значительно им увеличить энергопотребление, как с двигателями на антиматерии. Можно ещё сделать ослабленную копию этих стабилизаторов и выпустить их для игроков? Тогда не надо ничего менять. 

Therefore, I suggest that they significantly increase their energy consumption, as with antimatter engines. Is it still possible to make a weakened copy of these stabilizers and release them to the players? Then there is no need to change anything.

**Comment by PavelZinchenko** [comment]
Added 3x3 inertial nullifiers with that reduce mass by 4500
