### ISSUE TITLE
Salvage drone is not immune to weapon's effects

### ISSUE THREAD

**Issue by NerdyQT** [PavelZinchenko/event-horizon-frontier-builds#24]
Salvage drones are affected by emp nuke, switch to berserk mode and collide with player's ships and starbase, causing them to get stuck when gathering loots. They can also be pulled by Blackhole or captured by Drone Capture System. This should not be happening and Salvage drones should be immune to all effects like how they are immune to damage.

Video: https://streamable.com/3jq7n8

**Comment by PavelZinchenko** [comment]
I made salvage drones immune to nuke and capture systems.
They are still affected by some other effects, but it's difficult to fix, and I don't believe it's worth the effort.
