### ISSUE TITLE
New auto-fire feature causes delay between unpressing button and game realising it is not pressed

### ISSUE THREAD

**Issue by Zen9890** [PavelZinchenko/event-horizon-frontier-builds#242]
This bug currently only applies to the manageable and chargeable weapons, and feels very dissatisfying gameplay wise
Steps to reproduce:
1) Install black hole generator/frag bomb/tachyon beam
2) tap the button to fire quickly
3) There is delay between tap and BHG/frag bomb detonating
Game version: 2.9.5 build 1930

**Comment by Inedilarion** [comment]
You can replace the double tap with a swipe down/up/to a new button (for example, “drag” the fire button to the pop-up lock). Or make this option for turning on auto-fire additional, with the possibility of activating it in the same place where you can now disable auto-fire by double-tap

**Comment by PavelZinchenko** [comment]
I've removed the delay for chargeable and controllable weapons
