### ISSUE TITLE
Бонус от прокачки учёного до 100 уровня остался

### ISSUE THREAD

**Issue by Inedilarion** [PavelZinchenko/event-horizon-frontier-builds#243]
Урон оружия и хп брони сильно больше чем должны быть
![Screenshot_2024-05-17-21-35-47-446_com ZipasGames Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/66635560/2d732fb9-5bbf-44fc-af31-ff89d454340e)
![Screenshot_2024-05-17-21-40-19-973_com ZipasGames Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/66635560/8505604c-0052-4c64-ade3-b6f748b9046c)

**Comment by PavelZinchenko** [comment]
У меня такого нет. Скорее всего после перезахода в игру хп придет в норму.

I believe restarting the game will solve the issue

**Comment by Inedilarion** [comment]
Да, после перезахода характеристики пришли в норму. Но на арене сейчас появилось много соперников с такими бустами орудий и брони (проверял пока они были и у меня)
