### ISSUE TITLE
Scavenger drone speed too slow.

### ISSUE THREAD

**Issue by magne00** [PavelZinchenko/event-horizon-frontier-builds#244]
Since we now have;
 
-"all come here" button which makes enemies appear faster (very fast drops)
-Scavenger perk (lots of resource drop)
And
-enemies that spawn very far from base

I think it's time to buff Scavenger drone speed so it can catch up to the drops before they disappear (even STARS!).

**Comment by magne00** [comment]
Forgot to add... They sometimes hit each other making them more slow.

![Screenshot_20240517_164954_Event Horizon - Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/165588331/0c26c2d2-a71f-45fa-8627-f172e05df591)

In this screenshot both of them are stuck and did not move.

**Comment by vlad-ultramarine** [comment]
drones collide with them too

**Comment by magne00** [comment]
True. If one has a ship carrier and a research station (with drones) ot becomes even more slower

**Comment by YoshiNo2-0** [comment]
It may be possible to increase the collection radius so that the drone collects several resources at once at the point of death of the bots, rather than accelerating behind each of them

**Comment by vlad-ultramarine** [comment]
like player ship thing, yeah

**Comment by TaipionsSalemClient** [comment]
yes, please, but it's not the  only issue, I'll make another one though

- drones too slow
- turn rate too bad (real problem!)
- reset/respawn upon closing end screen
- not big enough loot collection radius
- collisions
- ...

**Comment by vlad-ultramarine** [comment]
можешь убрать первые 2 пункта

**Comment by magne00** [comment]
Scavenger drone fast. Scavenger drone good. Men happy.
