### ISSUE TITLE
Exploration difficulty

### ISSUE THREAD

**Issue by Snowgods** [PavelZinchenko/event-horizon-frontier-builds#253]
Adding triple vet units to exploration missions makes them ridiculously hard. 
At close to Level 500 where I currently am the opponent's difficulty is close  to the player's max level bonus..
They already massively outnumber me.  That's Fine, I can handle that. What I don't like is spending a full minute to kill 1 opponent, only to have to do it over and over again, with little reward. Games should be fun, even at high level.

build 1937

**Comment by PavelZinchenko** [comment]
Significantly reduced the number of these ships in explorations and increased the loot they can drop
