### ISSUE TITLE
2.9.5 APK not appearing

### ISSUE THREAD

**Issue by Lupuu0102** [PavelZinchenko/event-horizon-frontier-builds#254]
![Screenshot_2024-05-19-17-15-19-83_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/166023496/43ba3e0e-8dc1-49b9-82f2-c5f2cbb596c4)

**Comment by PavelZinchenko** [comment]
I just found a bug that needs to be fixed. I'll upload a new version in a few minutes.
