### ISSUE TITLE
The AI is broken

### ISSUE THREAD

**Issue by Kipyatochkov** [PavelZinchenko/event-horizon-frontier-builds#255]
Если зайти в бой, то можно увидеть, что корабли игрока просто летают вокруг базы, игнорируя врагов. Такая ситуация на уровнях и на арене, но на арене этот баг и у соперника. Также сломался автопилот.
Build 1942

If you go into battle, you can see that the player's ships are just flying around the base, ignoring the enemies. This is the situation at the levels and in the arena, but in the arena the opponent has this bug. The autopilot also broke down.
Build 1942

**Comment by Bezbasheniy** [comment]
В прохождении ии тоже не работает. Некоторые корабли даже забывают за чем они заспавнились, зависают в километрах от базы и ничего не делают, в то время как дружественный ИИ также ничего не делает, либо стреляет в противлположную сторону.
