### ISSUE TITLE
Railgun,Heavy railgun and Heavy laser cannon buff

### ISSUE THREAD

**Issue by Absolutan115** [PavelZinchenko/event-horizon-frontier-builds#261]
Railgun and Heavy railgun are the worst kinetic weapon,need buff:

-Damage increase by 100% velocity increasing by 50%

Heavy laser cannon need special effect like HLC (shutdown enemy energy recovery)

-when hit a target 3 second, burn effect activated damage increasing by 40% last in 3 second if not hit.

**Comment by PavelZinchenko** [comment]
railgun 45 -> 100
heavy railgun 80 -> 200
heavy laser beam now has progressive damage witch is 50 at start and gradually increases to 100 in 3 sec if hitting the same target

**Comment by Absolutan115** [comment]
Nice
