### ISSUE TITLE
[Enhancement] Vampiric Rays

### ISSUE THREAD

**Issue by nvcbl** [PavelZinchenko/event-horizon-frontier-builds#266]
Currently, the regular Vampiric Ray isn't very useful in the later game, as while you'll eventually kill even a red harbour with enough rays, it'll take a while, which will make you vulnerable to other things, like EMPs and other ships (and drones in the case of the red harbour). Here are the things i suggest you doing about it:

- Make the HVR in the Tartarus available for players, while changing the HVR in it to the M2 Variant
- The above but without changing the Tartarus' weapon to an HVR M2 (Make it available but keep the one on the Tartarus a regular one)
- Create a weaker variant while keeping the one on the Tartarus (less damage, more energy consumption, or both)
- Buff the regular Vampiric Rays

**Comment by Thirteen0130** [comment]
Мне не нравится. Это единственнре оружие в игре, доступное игроку, эксклюзивное, единственное. А добавление его меньших аналогов уничтожит его неповторимость. Если хотите улучшения, то просто поменяйте урон на коррозионный, что более логично, чем энергетический, который вообще здесь лишний. Не реально, оружие, которое ворует здоровье, наносит энергетический урон. Это глупо.


I don't like. This is the only weapon in the game available to the player, exclusive, the only one. And adding its smaller counterparts will destroy its uniqueness. If you want to improve, then just change the damage to corrosive, which is more logical than energy, which is generally superfluous here. Not really, a weapon that steals health does energy damage. It's stupid.

**Comment by Inedilarion** [comment]
Единственным нормальным пунктом является последний, синтез-лучи сейчас абсолютно бесполезны и никем никогда не используются

The only normal point is the last one, vampiric rays are now absolutely useless and are never used by anyone
