### ISSUE TITLE
Revert Starbase Defense Back To Normal

### ISSUE THREAD

**Issue by IsmollCheeKen** [PavelZinchenko/event-horizon-frontier-builds#267]
This is my fleet against the Top 1 in the Arena Leaderboard, battle resulted in a tie with the time running out. This is really bad.

![Screenshot_20240525_150132](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164343919/171fe8bf-8e2c-40c7-8d7d-098b040403c1)

Also, it has already been made apparent from issue #231 that the option 'buff starbase defense' is in the minority and it is not wanted. So, why was it added anyway?

![Screenshot_20240525_114555](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164343919/caca7ba0-d490-4431-8557-6e762d3a666a)

**Comment by tsn0710** [comment]
You lose not because you are weak, but because your opponent's repair ray is strong. So I suggest nerf repair ray.
I support the idea of buffing the starbase because I want to see more Scientist SB and Infected SB in pvp mode.
I want scientist SB's energy cooldown time to be reduced to less than 1 second. 
I want the repair cooldown time of Infected SB to be reduced to less than 1 second.

**Comment by tsn0710** [comment]
My idea about nerf repair ray is:
- max Hit Points of SB is M
- when your SB got hit with damage is X
- Then the new max hit points of your SB:   M = M - 0.5 * X
Example: 
max hit point =100. After SB got hit with damage = 80, then the new max hit point is 100 - 0.5 *80 = 60. The real hp of your SB now is 100=80 =20, but it can got heal up to 60.

**Comment by magne00** [comment]
I suggest nerf it a little bit. The sb hp is too much.

**Comment by PavelZinchenko** [comment]
Repair rays highly benefit from resistances. If I reduce the amount repaired by the average resistance, it'll solve the problem. According to #231, I already nerfed AR. But the obstacle in the center won't solve the issue that the starbase is too fragile; it'll just let it live a few seconds more, so I decided not to do it.

**Comment by PavelZinchenko** [comment]
Decreased the starbase defense buff from the skill from 5000% to 3000%
