### ISSUE TITLE
[Request] Add a "Voting" section where the final proposals will be included. 

### ISSUE THREAD

**Issue by Bezbasheniy** [PavelZinchenko/event-horizon-frontier-builds#272]
Add a "Voting" section where the final proposals will be included. And subsequently, to accept for implementation only those proposals that were supported by at least five people. Such a system will serve as a safeguard against obviously bad and unbalanced ideas, and subsequently reduce the burden on the developer, as well as reduce the number of users dissatisfied with innovations

**Comment by PavelZinchenko** [comment]
While I consider every piece of feedback, the final decision on features rests with me. I believe that developing the game using voting is not the right way. Instead, I am implementing features that align with my personal vision for the game. Thank you for your understanding and support.

**Comment by Absolutan115** [comment]
Yeah
