### ISSUE TITLE
HEAVY LB progresive dmg didnt showed, allies ship not chase enemy when near complete.

### ISSUE THREAD

**Issue by Absolutan115** [PavelZinchenko/event-horizon-frontier-builds#280]
Please fix that Pavel😅

**Comment by PavelZinchenko** [comment]
Could you provide more details?

**Comment by Absolutan115** [comment]
![Screenshot_2024-05-28-17-19-12-356_com ZipasGames Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/142648525/129af944-8a6a-4b9b-9b5a-f5d862dfe1f4)

Progresive damage statistic not showed

**Comment by Absolutan115** [comment]
In campaign when enemy ship destroyed just last few ship 4-9, my allies ship doesnt target them anymore. So i need wipe out by my own ship. Sorry lack of detail.

**Comment by PavelZinchenko** [comment]
Are they in defensive mode? Defensive mercenaries don't target enemies that are far from the starbase.

The text indicates that the damage is progressive; it is not intended to display any numeric value.

**Comment by Absolutan115** [comment]
Oh sorry, my bad i Will close this issue.
