### ISSUE TITLE
Ai bug and Iq

### ISSUE THREAD

**Issue by Corsh** [PavelZinchenko/event-horizon-frontier-builds#282]
the ai does not attack when it approaches too close to enemy ship, only push it, the same applies for enemy
also the Ai iq has been deteriorated lately

**Comment by PavelZinchenko** [comment]
I've fixed the issue with attacking at close range. Regarding the AI deterioration, could you provide specific examples?

**Comment by vlad-ultramarine** [comment]
например: если у ии есть в распоряжении несколько орудий: например лазер и дальнобойные ракеты то если ему скорость не позволяет разорвать дистанцию то он пускай использует оба вида оружия, если скорость позволяет разорвать дистанцию то старается использовать ракеты. Хотя наверное ии уже так умеет
