### ISSUE TITLE
Limit of enhancement for everything is 20, not just defense and armor

### ISSUE THREAD

**Issue by Lupuu0102** [PavelZinchenko/event-horizon-frontier-builds#284]
I don't know if it's intentional, but the limit of enhancement for any stats of any module is 20, not 100 as it was supposed to be. I know that the limit for armor and damage is 20:

![Screenshot_2024-05-29-20-37-12-62_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/166023496/1e540c2a-e5ec-407c-b9f2-b1417a312313)

But:

![Screenshot_2024-05-29-20-42-17-19_48c014f8726d52b765b87002fd126ed8.jpg](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/166023496/576a2792-0e90-47a9-98cf-1ae9617688d8)

And it's not like the 20 of damage and armor, because it don't receive the same bonusses as these two.

**Comment by PavelZinchenko** [comment]
Bonuses for damage and armor are +10% / level
Bonuses for other stats +1% / level, but they are cheaper
