### ISSUE TITLE
buff and nerf for some weapons and module

### ISSUE THREAD

**Issue by Corsh** [PavelZinchenko/event-horizon-frontier-builds#289]
after the update the game become less balanced, lots of players including me complaints about it and demand a nerf and buff so here are some suggestions:
-increase the size of heavy antimatter torpedo by 2 cells and make it the same size as acid torpedo or make it only available for cruiser and above to prevent any ship can use and spam it
-remove or nerf the increase projectile speed upgrade for heavy railgun
-reduce knockback (not recoil) effect on heavy railgun and antimatter torpedo
-fragmentation bomb release 2 bomb projectiles instead of one, frag mechanic still the same
-heavy antimatter torpedo projectile easier to be destroyed by point defense module
-each clone center module after the first one which is 75% placed on ship reduce clone stats by 5% (the stats here are Hp and resistance)
-increase quantum torpedo projectile velocity
-automated reloader effects on long cooldown weapon reduced by half and cannot below 1-2 seconds 
-better autopilot ai
-velocity increase for heavy pulse canon m1 
-nerf emp nuke  
-nerf worm tail regenerate speed

**Comment by vlad-ultramarine** [comment]
clones already have 75% stats of original ship

**Comment by vlad-ultramarine** [comment]
no for antimatter torp because then I can't use it on iss galleon
