### ISSUE TITLE
energy leech harpoon change

### ISSUE THREAD

**Issue by Corsh** [PavelZinchenko/event-horizon-frontier-builds#291]
energy leach harpoon steal energy from latched target (also temporary pause energy regeneration from instant energy regeneration), when the target's energy depleted. you can either release or overcharge it which cost 5% of your energy per seconds by keep holding(maximum 50%), when release, the harpoon explode, which unlatched the target, force 3 seconds of energy regeneration cooldown and deal damage equal to 25% of energy stolen + your overcharge energy.

**Comment by vlad-ultramarine** [comment]
"steals energy from enemy" "began consuming 5% of your total energy"

**Comment by Corsh** [comment]
> "steals energy from enemy" "began consuming 5% of your total energy"

5% total energy per second is to overcharge the harpoon, the harpoon explosion deal 25% of your overcharge energy + energy stolen

**Comment by Corsh** [comment]
e.g if you have 1000 energy capacity, you can overcharge the harpoon with 500 energy maximum with the rate of 25 energy per sec
