### ISSUE TITLE
Heavy ion Cannon Mk 2 buff

### ISSUE THREAD

**Issue by Absolutan115** [PavelZinchenko/event-horizon-frontier-builds#292]
HIC mk2 use a lot of energy but nearly same damage and aoe with HIC, buff HIC mk2 aoe from 6 to 8 or 10. It Will become late game fast projectile with big aoe instead using Heavy plasma emitter.

**Comment by magne00** [comment]
The weapon is already strong as it is. There is no reason to buff it further.

**Comment by Absolutan115** [comment]
Ok i Will close this issue
