### ISSUE TITLE
All friendly ships have green star on them

### ISSUE THREAD

**Issue by Pomeha-TLA** [PavelZinchenko/event-horizon-frontier-builds#3]
![Screenshot_20240217-211732](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/152905218/7cbae58b-61f2-4165-a487-f02e69107811)
If it exists to show friendly ships its better for them to have green outline or something like this

**Comment by NerdyQT** [comment]
There should also be a toggle to turn this feature on/off

**Comment by PavelZinchenko** [comment]
I removed stars from drones and clones. Only mercenaries and merchants have them for now. It doesn't look as annoying anymore.
