### ISSUE TITLE
ship blueprint 

### ISSUE THREAD

**Issue by korshard** [PavelZinchenko/event-horizon-frontier-builds#304]
replica ship blueprint can be used to expand that ship's module slot for free, the blueprint point stay permanent and can be reset any time

**Comment by Thirteen0130** [comment]
Ты о чём вообще?

**Comment by korshard** [comment]
to prevent farming ship blueprint from citadel, after the ship unlocked, blueprint drop rate of that citadel is set to 5%

**Comment by Corsh** [comment]
to prevent farming ship blueprint from citadel, reduce the chance of drop rate to like 5%
