### ISSUE TITLE
Question about satellites, and a request for them as well

### ISSUE THREAD

**Issue by SuplexCity25284** [PavelZinchenko/event-horizon-frontier-builds#306]
Is the Hovertank satellite still available?  I used to see it in the smuggler sometimes, but I haven't in forever... like 6 months.

Also, if it is, are there others like it, but dedicated to other weapons, like torpedo, missile, beam, special?

If not, I would love to see something similar in future updates.

Also, I had a thought about making more styles of smaller class satellites.  We have mk1, 2 and 3, but what about subclasses with the same weapon types, but more orientation differences so we could have more varied weapon setups.   Maybe a satellite with 3 across by 2 high, so you could mount 3 small cannons, or whatever other style you can think up.

**Comment by Snowgods** [comment]
Yes, Hovertank still exists, there is also Iron ball for L type weapons, and Powerbank, for green slots.
They are a high level drop  in exploration missions, or rarely in the black bazaar 5 shop (Highest PVP arena shop)

**Comment by SuplexCity25284** [comment]
There isn't one for torpedo weapons?  Hmm, interesting. 

How high level of a drop are they?  I'm in 141-5 currently.

**Comment by Snowgods** [comment]
Sorry, don't know the minimum drop levels. I'm up above 500, and they're fairly common there.
Both the Iron ball, and the Powerbank are new, Parvel may develop more variants in time.

**Comment by SuplexCity25284** [comment]
Is the hovertank still available on occasion in the smuggler store?
