### ISSUE TITLE
[BUG] Broken Smuggler Shop

### ISSUE THREAD

**Issue by IsmollCheeKen** [PavelZinchenko/event-horizon-frontier-builds#309]
![Screenshot_20240609_005907](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164343919/d00f3ce5-0b5e-40ff-90b2-b9328a626a65)

**Comment by SuplexCity25284** [comment]
I've had this happen too.  It usually fixes if I exit, fly my ship away a moment, fly back to the smuggler, and reenter the store
