### ISSUE TITLE
Anti-Cheat Not Working

### ISSUE THREAD

**Issue by IsmollCheeKen** [PavelZinchenko/event-horizon-frontier-builds#311]
Mmmhmmm
![Screenshot_20240609_184003](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164343919/26eb45e3-ab53-40d4-99cb-b3e66446400a)

Uh huh...ok
![Screenshot_20240609_184126](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164343919/f21e482b-9d20-4584-8d89-0e729f484733)

What the hell happened to the Anti-Cheat!?
https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164343919/d9ec9bea-725d-481f-a9ff-4bc10c6d5539

ChaosFred fleet in Arena, there was no cheater warning that appeared before the battle...

**Comment by IsmollCheeKen** [comment]
Another one of Fred's rogue fleets.
![Screenshot_20240609_224320](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164343919/aa941526-9e3d-4867-8e74-5bdf8c4d0388)

Fred does not have control over both Infinite Kimochi and ChaosFred fleet accounts, they are rogue duplicated fleets caused by an old glitch in the beta versions (there was at one point existed 5 different EinHeart fleets because of the glitch).

But the real mystery is, these fleets have existed before the Arena database wipe. So why are they back even after the wipe? Was there never a wipe in the first place? If so, then why? And why aren't these fleets getting flagged?

**Comment by HackON777** [comment]
This is not a cheater. This is an old version of the game and the fleet

**Comment by Snowgods** [comment]
It can't be am old version, as old versions are currently blocked from PVP, 
I don't see it getting fixed in a hurry, as there has been no reply from my  2 week old Einhearts issue, and his billion health base.
