### ISSUE TITLE
[Request] new weapon

### ISSUE THREAD

**Issue by Absolutan115** [PavelZinchenko/event-horizon-frontier-builds#317]
We need larger weapon.

The ULTIMATE late game weapon for Capital Ship or even beyond (from my mind).

Heavy Machine Gun,(the improved machine Gun)
3×4 (12 slots)

-Kinetic Damage 15×30 per second
-Range 50
-Velocity 100
-Energy cost 30
-Weight (adaptive)
-Projectile color (cyan)

Gamma Ray Burst Laser (the wide and long range laser Ray)
3×6 (18 slots)

-Hybrid(All type)Damage 1000=4000 (Kinetic,Heat,Energy,and Corrosive)
-Range 120
-Cooldown 40 second
-Energy cost 500
-Area of effect 20
-Weight (adaptive)
-Laser color (Green in outer color and white in inner color)

Heavy Nuke Missile (a thermonuclear weapon) 
2×6 (12 slots)

-Heat damage 1000
-Kinetic damage 500
-Range 50
-Velocity 40
-Cooldown 20 second
-Energy cost 200
-Area of effect 100
-Weight (adaptive)
-projectile color (white red)

You can nerf or buff this thing if to op or weak.
Remember just in my own thinking (you can reject it).

**Comment by Tree3324417** [comment]
"We cant have enough overpowered things made from horribly bad balance decisions, so here is some more edgy insanely overpowered things i hope you would enjoy."

What.

Quoting ChaosFred on Discord
> Please suggest a more unique weapon rather just enhanced "small plasma webs -> large plasma webs
