### ISSUE TITLE
Player with Attack Rating Over Limit in Arena

### ISSUE THREAD

**Issue by IsmollCheeKen** [PavelZinchenko/event-horizon-frontier-builds#323]
The Arena Attack Rating has a limit of 100k+4.5k (104500), the Top 1 player with a blank name in the image below is clearly above this limit
![Screenshot_20240619_110835](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164343919/a1b2eb62-3acf-4297-9000-0e19c1e3efd3)

At Attack Rating 100k+4.5k, you should not be able to get anymore rating from battles against 100k Defense Rating opponents. So the only explanation is cheating.

For context: at 100k Attack Rating, battles against 100k Defense Rating opponents will yield 9 points, and the yield decreases by 1 for every 500 increment in Attack Rating.
Ex: (against 100k Defense Rating opponents)
100k Rating = +9 points
100k+500 Rating = +8 points
100k+1k Rating = +7 points
100k+1.5k Rating = +6 points
100k+2k Rating = +5 points
And so on....until 100k+4.5k = +0 points, therefore making 104500 rating the limit.

I called him out on it, and he decreased his rating, this is the current state of the Starbase Battle Leaderboard as of making this issue:
![Screenshot_20240619_222258](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164343919/78bad55c-1b3e-4d94-95e2-b08c1a46a03f)
He still has a rating above 104500

**Comment by SuplexCity25284** [comment]
I just saw what you mentioned here just now.

A player who is in the hall of fame woth no visible name, had a attack of 105392.
