### ISSUE TITLE
weapon ideas

### ISSUE THREAD

**Issue by SuplexCity25284** [PavelZinchenko/event-horizon-frontier-builds#331]
Was tooling around with weapons and it occurred to me that there are missed opportunities for new weapons:
Heavy neutron blaster mk2
Neutron blaster mk3
Mass driver mk3 or heavy mass driver 
Cluster missile mk2
Small pirate cannon (same size as energy wave, perhaps) 
  If any of these exist and I haven't yet found them, please let me know.

**Comment by External-Amit** [comment]
We don't need upgraded versions of such weapons instead of few endgame weapons. That's confirmed.

**Comment by SuplexCity25284** [comment]
I'll take any weapons I can get to get an advantage, BUT, yes, I can see how the endgame levels would need better weapons too.  I'm only at level 156, and some weapons just don't cut it.c that's why I am suggesting newer ones

**Comment by Absolutan115** [comment]
Well new weapon like Gamma Ray Laser (Hybrid damage), Thermonuclear Missile (Heat damage), Zeus Thunderstorm (Energy damage), Decimator (kinetic damage) or whatever.

**Comment by Absolutan115** [comment]
I am at level 409 have any weapon, and feel boring. Thats why I really want new endgame weapon

**Comment by Absolutan115** [comment]
![Screenshot_2024-06-29-20-41-32-335_com ZipasGames Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/142648525/5183cd7a-b017-42fb-a3ec-69c240838b34)
![Screenshot_2024-06-29-20-42-11-542_com ZipasGames Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/142648525/034e00a0-c634-46f9-a681-4e26e26490e0)

**Comment by SuplexCity25284** [comment]
I have the heavy plasma emitter, and like it.  I'm guessing a mark 2 would be more to what you need though

**Comment by SuplexCity25284** [comment]
Another weapon idea I just had, is twinned cannons, of any type, a double barreled plasma cannon or neutron cannon, either rhat takes up more slots, or takes the same, but is much heavier.  That or add some rotary cannons as higher level items, like a future version of a Vulcan cannon or GAU/8 Avenger.  

And I would kinda love, since I'm a trekkie, something akin to pulse phasers.

And finally a question, some weapons combine damage types, ie: kinetic and heat, or energy and heat.  Do any combine 3 types?  Also, in a future update, it would be cool to have, unless it's in game already, something that combine corrosive with another damage type.  If they exist, I've yet to find them.

**Comment by Absolutan115** [comment]
4 combine damage is Hybrid damage

**Comment by SuplexCity25284** [comment]
I've yet to find anything like that

**Comment by Absolutan115** [comment]
Yeah Hybrid damage still not exist

**Comment by SuplexCity25284** [comment]
> Yeah Hybrid damage still not exist

I kinda thought that.
