### ISSUE TITLE
weapon idea: cluster plasma web

### ISSUE THREAD

**Issue by SuplexCity25284** [PavelZinchenko/event-horizon-frontier-builds#339]
We already have cluster missile, cluster torpedoes, what about cluster plasma web, for special weapons?

Make it, idk 1x6 slots, or 2 x 4, and it would fire, blow up much like cluster torpedo but instead scatter several smaller plasma webs.

**Comment by Dynamo10101** [comment]
Do you want to add more annoying weapons to the game? 
We already have BHG and normal plasma webs

**Comment by SuplexCity25284** [comment]
I just want more options, BUT, if people think it would be annoying, then, ok.  Not a problem
