### ISSUE TITLE
rear admiral perk

### ISSUE THREAD

**Issue by SuplexCity25284** [PavelZinchenko/event-horizon-frontier-builds#367]
I kind of miss it.  

I mean, it had value, being able to make your fleet a bit bigger.  Now, to me, thec30 point cap seems limiting sometimes, especially when at level 235 as I am, I'm facing Syberias both vet and triple vet, jormungandr in triple vet form, etc, having rhe extra firepower and defense of an extra ship or two would be of benefit.

What do you all think?

**Comment by TaipionsSalemClient** [comment]
> I kind of miss it.
> 
> I mean, it had value, being able to make your fleet a bit bigger. Now, to me, thec30 point cap seems limiting sometimes, especially when at level 235 as I am, I'm facing Syberias both vet and triple vet, jormungandr in triple vet form, etc, having rhe extra firepower and defense of an extra ship or two would be of benefit.
> 
> What do you all think?

I think you missed a lot, your concerns are completely invalid, and you just need to "grind more" to progress.

Rear-Admiral perk is now applied to EVERY pilot, meaning all pilots act as if they have the perk (-1 command point cost) by default.

I can assure you that there is no level in the playable area of the game (up to about lvl 2000) that is not beatable,
you just need to do the usual things to increase your fleets power.

**Comment by SuplexCity25284** [comment]
Well thanks for just kinda insulting me?

I'm kidding.  BUT you also right, to an extent.

**Comment by xdeadstokex** [comment]
@SuplexCity25284 The first time real admiral was added I immediately thought of a frigate army (like every one of them) and to counter pilot cap I just need luck in exploration, well, it didnt last long enough till the next update drop :D
