### ISSUE TITLE
Iron ball satellite

### ISSUE THREAD

**Issue by Inedilarion** [PavelZinchenko/event-horizon-frontier-builds#41]
Данный спутник слишком сильный, помимо возможности установки мощнейшего оружия в игре, большой разрядной пушки, в турель полного вращения (что раньше было доступно всего 2 титанам без учёта модификации на всё оружие, ослабляющей урон), он имеет 8 мест под модули размером 2х2 в зелёные клетки, вчетверо больше любого старого спутника. А также он уменьшает разнообразие сборок, потому что самой эффективной сборкой для титанов становится установка оружия в эти спутники игнорируя собственное оружие корабля. Ну и он неоправданно силён для встречающихся в волнах врагов, которых и сейчас на уровнях до 1000 зачастую может за пару минут зачищать один-единственный титан на автопилоте (как показано в [issue_14](https://github.com/PavelZinchenko/event-horizon-frontier-builds/issues/14))

This satellite is too strong, in addition to the ability to install the most powerful weapon in the game, heavy lightning cannon, in a full rotation turret (which was previously available to only 2 titans without modification for all weapons that weakens the damage), it has 8 places for 2x2 modules in green cells that four times larger than any old satellite. It also reduces the variety of builds, because the most effective build for titans is to install weapons in these satellites, ignoring the ship's own weapons. And it is unreasonably strong for enemies encountered in waves, which now at levels up to 1000 can often be cleared in a couple of minutes by a single titan on autopilot (that shown in [issue_14](https://github.com/PavelZinchenko/event-horizon-frontier-builds/issues/14))

**Comment by Kipyatochkov** [comment]
Лучше просто ослабить тяжёлую разрядную пушку (уменьшить урон искр в два раза, а число уменьшить до 8, например) и сделать этот спутник менее доступным (видел, как его выдали за ежедневный вход). Ну, а если ослаблять спутник, то можно сделать половину 2x2 клеток синими, а вторую зелёными, например.

It is better to simply weaken the heavy lightning cannon (reduce the damage of sparks by half, and reduce the number to 8, for example) and make this satellite less accessible (I saw how it was given out as a reward for daily entry). Well, if weaken the satellite, then can make half of the 2x2 cells blue, and the second green, for example.
