### ISSUE TITLE
Новая система прокачки

### ISSUE THREAD

**Issue by Thirteen0130** [PavelZinchenko/event-horizon-frontier-builds#46]
Объясните мне, у учёного написано, что "улучшаются все модули в игре", это значит, что даже у ботов и врагов? В пвп если у врага тоже есть прокаченные модули от учёного и у меня есть, то у каждого будет своё?

**Comment by PavelZinchenko** [comment]
Прокачиваются только модули игрока и наемников. У врагов нет улучшений. У противников на арене свои улучшения.
