### ISSUE TITLE
Old modules +X

### ISSUE THREAD

**Issue by Thirteen0130** [PavelZinchenko/event-horizon-frontier-builds#49]
Что будет со старыми модулями, прокаченными до +20? Они исчезнут? Столько звёзд было потрачено не для того, чтобы они потом исчезли! 

What will happen to the old modules upgraded to +20? Will they disappear? So many stars were not spent so that they would disappear later!

**Comment by juh9870** [comment]
Please refer to the discussion https://github.com/PavelZinchenko/event-horizon-frontier-builds/discussions/44#discussioncomment-8886743
