### ISSUE TITLE
heavy vampiric ray blueprint

### ISSUE THREAD

**Issue by vlad-ultramarine** [PavelZinchenko/event-horizon-frontier-builds#57]
с добавлением новой системы прокачки все модули "+" обмениваются на чертежи, звёзды и кредиты. И соответственно можно получить в обмен на + прокачку тяжёлого синтез луча его чертежи и спокойно его создавать у инженера, и ставить куда хочешь

**Comment by Thirteen0130** [comment]
Тогда ещё одна проблема:чтобы улучшить, нужны чертежи. А их для тяжёлого вампир луча их нет. Тогда как улучшать вампирский луч?

**Comment by PavelZinchenko** [comment]
вампирский луч теперь улучшается без чертежей
