### ISSUE TITLE
[Bug] Satellite Perk does not work on Frigate Class Ships

### ISSUE THREAD

**Issue by TaipionsSalemClient** [PavelZinchenko/event-horizon-frontier-builds#63]
As the title says, the satellite upgrade perk does not work on frigates

(it is not select-able)

**Comment by Zen9890** [comment]
In EHF destroyers can equip M1 satellites only aswell, so installing this perk on frigate effectively will do nothing

**Comment by TaipionsSalemClient** [comment]
> In EHF destroyers can equip M1 satellites only aswell, so installing this perk on frigate effectively will do nothing

That may make sense from your point of view, but it does not from the point of view of most players.
The wording of the perk suggests to be able to use the next higher satellite, not the satellite of the next higher ship class.

In addition, it just does not make sense, why prohibit this perk from use on frigates?
using a med over a small sat is not much, and there are not many useful frigates anyways,
and this perk could help alleviate this.

**Comment by Zen9890** [comment]
> > In EHF destroyers can equip M1 satellites only aswell, so installing this perk on frigate effectively will do nothing
> 
> That may make sense from your point of view, but it does not from the point of view of most players. The wording of the perk suggests to be able to use the next higher satellite, not the satellite of the next higher ship class.
> 
> In addition, it just does not make sense, why prohibit this perk from use on frigates? using a med over a small sat is not much, and there are not many useful frigates anyways, and this perk could help alleviate this.

The way satellite sizes are limited per ship class internally in files wouldnt really allow you to make this happen, unless Pavel special-cases frigates to be treated two classes higher than they are with perk

**Comment by PavelZinchenko** [comment]
I enabled this perk for frigates in the latest Google Play beta version, allowing them to install M2 satellites.
