### ISSUE TITLE
+X Modules Conversion Issue pt.2

### ISSUE THREAD

**Issue by IsmollCheeKen** [PavelZinchenko/event-horizon-frontier-builds#65]
The latest Beta update have given the correct Star compensation on modules installed on ships/Starbases, it also converted +X modules in the storage. HOWEVER it did not give compensation for modules converted in storage. This is an even major issue than before, please fix this ASAP. Thank you.

**Comment by Anarkill1** [comment]
Theres  bug in the daily rewards too and when the game gives a high level mosule it bugs
![Screenshot_20240326-003759](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164980010/f3ddc7f3-3a07-4dbe-9c51-60a1e543a91d)
