### ISSUE TITLE
Disable 'Auto-Save To Cloud' by Default

### ISSUE THREAD

**Issue by IsmollCheeKen** [PavelZinchenko/event-horizon-frontier-builds#67]
There have been many cases where people have lost their save files due to the 'Auto-Save To Cloud' function being enabled by default when they re/install the game. One such instance is the man in the screenshot provided below:

![Screenshot_20240327_021713](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164343919/8eef73aa-eb37-479e-a55e-44e5987266b8)

Simply disabling the 'Auto-Save To Cloud' function by default at the game's installation would prevent such incidents.

**Comment by IsmollCheeKen** [comment]
Here is another person who lost his save file due to this problem.

![Screenshot_20240327_023231](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164343919/ce8b545d-0330-4e05-865c-0a5cee722838)

**Comment by PavelZinchenko** [comment]
Disabled it in the latest version.
Additionally, I've set up a discussion thread for individuals who've lost their progress.
#69 Lost Your Progress?
