### ISSUE TITLE
[Suggestion] Engineer-like perk for Scientist

### ISSUE THREAD

**Issue by GearGuardian91** [PavelZinchenko/event-horizon-frontier-builds#68]
I have noticed that when using the scientist to upgrade items, it guarantees that you lose a blueprint. The engineer perk reduces blueprint consumption rate for mod upgrades to 25% while the stat upgrade (scientist) does little in comparison, but guarantees you lose a blueprint, and with blueprints for rarer weapons (black hole generator, heavy lightning cannon, etc.) not dropping nearly as often as needed to upgrade anything sufficiently, wouldn't it help to extend the engineer perk's boost to the scientist?

**Comment by vlad-ultramarine** [comment]
better just add same perk but for scientist, i have 600+ not used skill points
