### ISSUE TITLE
[Suggestion] Fleet Loadouts / Tabs

### ISSUE THREAD

**Issue by TaipionsSalemClient** [PavelZinchenko/event-horizon-frontier-builds#70]
Similar to the Loadouts for ship fittings.
Saves assignment of ships to pilots/you
Saves setting defensive/offensive for pilots

Can be either:

1.) (probably easier to do) Same Loadout UI as on the ship fittings with save/load

or

2.) (preferred) Tabs right side next to the command points in the fleet window,
this would allow for 3-5 tabs for different fleets and would be much quicker to access than the save/load-UI,
and would prevent accidentally overwriting or deleting your loadouts if the tabs are just fixed

This way you can quickly change between pve fleet and arena fleet with one click (2.Tabs) or just a few clicks (1.save/load-UI),
and also select your exploration ship quickly without having to scroll through **the entire list of ships**, and then again through the **entire list of ships** to re-select your main ship and **again** to assign your exploration ship to a merc if it is also in your fleet.
This would be great QoL for comparably little work. :3

**Comment by PavelZinchenko** [comment]
Done. In a slightly different way, but it still resolves the issue.
