### ISSUE TITLE
Баг с новой торпедой 

### ISSUE THREAD

**Issue by MisterN13** [PavelZinchenko/event-horizon-frontier-builds#73]
При поражении базы новой торпеды она телепортируется. Мне кажется такого быть не должно. Если все же это так задумано, то нужно перемещать точки спавна врагов, иначе они двигаются с одного направления и далеко от базы.

**Comment by vlad-ultramarine** [comment]
![Screenshot_20240327-130640](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/163786031/1ea8360b-7a36-4300-85e9-a20c7185f5cd)
