### ISSUE TITLE
Heavy Plasma Emitter able to pierce Super Asteroid on Arena battlefield

### ISSUE THREAD

**Issue by Pomeha-TLA** [PavelZinchenko/event-horizon-frontier-builds#77]
https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/152905218/23470f5e-716d-4fda-b2e5-c9cbd1945205

Many other weapons are fine and not able to pierce it but HPE can

**Comment by vlad-ultramarine** [comment]
это фишка пушки как бы что она пробивает противников и астероиды

**Comment by Pomeha-TLA** [comment]
Super Asteroid is no more
