### ISSUE TITLE
[Enhancement] anticheat for Arena mode

### ISSUE THREAD

**Issue by Pomeha-TLA** [PavelZinchenko/event-horizon-frontier-builds#79]
In top 10 there's player with cheated fleet
Player's name ChaosFred
Has 3 Jormungards and nearly invincible starbase

Arena need some kind of anticheat that will at least check if it is possible for player to get some fleet they have without using some kind of cheats

**Comment by TaipionsSalemClient** [comment]
check number and type of ships,
check stats, too

**Comment by Inedilarion** [comment]
ChaosFred fleet now. Turret with extremely powerful repair beam

https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/66635560/4dc0de63-08ab-4111-8122-34ab94dd175e
