### ISSUE TITLE
Drill Sergeant Pilot Skill Replacement

### ISSUE THREAD

**Issue by IsmollCheeKen** [PavelZinchenko/event-horizon-frontier-builds#80]
The removal of the Rear Admiral has caused quite a stir among the veterans of Frontier. Especially since it has been replaced with the Drill Sergeant skill, a completely unusable pilot skill for veteran players - suddenly wasting a skill slot which could instead be something else, like Cannoneer/Armourer.

To put this into context, before the change, the BEST pilot you could ever have in the game is with the skills Specialist + Technician + Rear Admiral. Naturally, all of us veteran players have searched for mercenary pilots with these particular set of skills, and we have spent thousands of stars refreshing the mercenary shop and hiring the pilots themselves.

Then suddenly, the Rear Admiral (usable) skill has been replaced with the Drill Sergeant (unusable), a completely unusable skill that gives NO benefit to players once you have maxed all the levels, of course this is the case for us veterans.

Now, this change compels us to replace our pilots with another that doesn't have an unusable skill if we want to stay among the strongest players. We will be forced to spend more Stars refreshing the mercenary shop, and even more Stars hiring new pilots, not to mention the amount of hours we have to spend searching for another specific pilot.

Take my pilots as an unfortunate example:
![Screenshot_20240327_190409](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164343919/1128207e-1b48-4496-a7c1-59d0307d077c)
![Screenshot_20240327_190431](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164343919/2ecd2ee0-f8a2-4321-b769-1ab1113dd5c0)

All 16 of my pilots had Rear Admiral on them, now that it has been replaced with something unusable, I am now suddenly compelled to replace ALL 16 pilots just to get rid of that unusable skill. This is the same case for every veteran player that had Rear Admiral on their pilots.

So here's what I suggest:
• Replace Drill Sergeant skill to something more useful.
• Or, give us the ability to change specific pilot skills for a decent fee.

**Comment by IsmollCheeKen** [comment]
TL,DR:
We spent thousands of Stars and hours of time to get the BEST pilots in the game, only for them to suddenly become mediocre at best, prompting replacement. This honestly seems unfair, and a punch in the gut for us veterans.

**Comment by PavelZinchenko** [comment]
There is a discussion thread where you can suggest "something more useful":
#74 "Rear-Admiral" replacement "Drill Sergant" is not adequate

**Comment by IsmollCheeKen** [comment]
With the latest addition of changeable mercenary pilot skills for a price, I believe this issue is now completed.
