### ISSUE TITLE
[Enhancement] making the scientist items and mission less tedious to finish or find 

### ISSUE THREAD

**Issue by Finront** [PavelZinchenko/event-horizon-frontier-builds#84]
The scientist mission is so tedious and annoying because the items needed are so rare to the point players give up. I suggest making the merchant in exploration have more quest items or hard levels drop the quest items  like survival levels. I'm writing this because other people find it annoying or quit and New players may quit early or don't progress anymore at some point. and other is because the scientist is necessary to progress deeper into the game. So it is necessary to make it less tedious so others can progress more.

**Comment by GearGuardian91** [comment]
just make the material drops more common, especially since the number you need for upgrades increases quite rapidly.

**Comment by MisterN13** [comment]
I collected all the items in just 30 minutes in the old update. Do you think it's impossible?) It's just that sometimes it's worth considering.
