### ISSUE TITLE
AI having control over modules that were set on auto

### ISSUE THREAD

**Issue by Pomeha-TLA** [PavelZinchenko/event-horizon-frontier-builds#9]
![Screenshot_20240224_151540_48c014f8726d52b765b87002fd126ed8](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/152905218/04f53513-940e-4f30-81be-98b322e5eaee)
Shield has 0% auto activation but when you give this ship to friendly AI it still able to set it off and use it just like there's no auto use

**Comment by PavelZinchenko** [comment]
same as #10
