### ISSUE TITLE
Real-life symbolic used on new ships 

### ISSUE THREAD

**Issue by juh9870** [PavelZinchenko/event-horizon-frontier-builds#91]
A new faction has IRL symbolics on their ships, which is the first time IRL symbolics was used, and I believe it is best to stick to purely fictional world.

I suggest using the snowflake symbol instead, since it is already part of the game, used on a starbase, as well as fits the ships theme pretty fine.

**Comment by Zen9890** [comment]
I think star symbol will work much better, because ships dont really look like Xmas faction
