### ISSUE TITLE
[Bug] Missing Material Lootbox

### ISSUE THREAD

**Issue by GearGuardian91** [PavelZinchenko/event-horizon-frontier-builds#92]
The lootbox for scientist materials doesn't appear in the shop with the other lootboxes. I have tried doing multiple explorations, levels and even reinstalling the game. 
![Screenshot_20240327-185545](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/163720452/e72a9c63-4fce-4998-8033-5b758f577939)

**Comment by PavelZinchenko** [comment]
It will appear when you complete the scientist quest

**Comment by GearGuardian91** [comment]
before my save was lost, it was available before i had finished the mission, as it is how i finished it (by buying it 3x). was that instance a bug, or was it because i was at a certain level?

**Comment by PavelZinchenko** [comment]
I changed it in one of the recent updates because it made the scientist quest too easy
