### ISSUE TITLE
Research station

### ISSUE THREAD

**Issue by MisterN13** [PavelZinchenko/event-horizon-frontier-builds#93]
Станция все еще телепортируются от новой торпеды. Остальные станции  профиксины.

Вообще она получилась немного слабой и очень простой. На ней максимум две стратегии можно использовать. Лично я рассчитывал на универсальный топ как минимум. У неё есть энергощит, который быстро заряжается . По факту он не очень эффективный с ботами которые часто используют эми . 
Если взять новогоднюю станцию использовать на ней тактику танка, то она прочнее будет в два раза и это при том что у неё есть воскрешение.
Может стоит на неё поставить шесть турелей? Чтоб хотя бы она могла стрелять или усилить её щит улучшением в магазе.
![Screenshot_20240329_164432_Event Horizon - Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/161188319/577bfdf3-2349-4ef3-82d0-953910bd526a)
![Screenshot_20240329_152118_Event Horizon - Frontier](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/161188319/683a6bc7-1401-42c5-8202-6dbf685144cd)

**Comment by Thirteen0130** [comment]
Вообще эта станция получилась неким аналогом рождественской станции. Только менее живучей. Одна емп бомба и всё. Нет её. Было бы хорошо, если были бы бонусы для дронов. База, специализированная для дронов ваще огонь.

**Comment by PavelZinchenko** [comment]
Добавил бонусы для дронов и усилил щит
