### ISSUE TITLE
Increase Resources Yield From Recycling

### ISSUE THREAD

**Issue by IsmollCheeKen** [PavelZinchenko/event-horizon-frontier-builds#96]
The Resources given by modules is too low, even for the commonly found modules. I recycled 2000+ gold small titanium armors and it only yielded 200+ resources.

![Screenshot_20240330_203622](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164343919/403b18d1-caef-4537-af7d-4fb3856b56bf)
![Screenshot_20240330_203627](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164343919/5f18db40-1631-48a1-8aba-5448fcbff5f2)

The case is the same for rarely found modules such as Interceptor Bays, and Parasite Spawners, they give too low resources. Please increase it.

Also please significantly increase the drop rate for Alien Artifacts, both in exploration and the Loot Box, as they are literally used for upgrades in ALL modules. I always find myself running out of them compared to other resources.

**Comment by imverybadatnames** [comment]
![Uploading 
![Screenshot_2024_0330_194805](https://github.com/PavelZinchenko/event-horizon-frontier-builds/assets/164344125/fe632f85-092a-4b28-8bf5-ad54fdcb0394)
Screenshot_2024_0330_194912.jpg…]()
Agreeed, i sold 16 gold interceptor hangars and got around 104 quantum chipsets, interceptir hangars are rare so the reward for recycling should have been higher.
