### ISSUE TITLE
Mercenaries are too weak

### ISSUE THREAD

**Issue by imverybadatnames** [PavelZinchenko/event-horizon-frontier-builds#98]
Compared to the player, mercenaries are weak, even with specialist, cannonneer and armourer, mercenaries are 3.45x weaker than player (6500%/1880%), and in the later stages, (>200-1), where enemies get stronger and more powerful, the mercenaries get outmatched by power and numbers, from my experience in level 472-5, i usually get 75% of the kills, and the mercenaries sometimes have more deaths than kills.
I would suggest to make the mercenaries more powerful, but not more powerful than the player, maybe making mercenaries 1.5x or 2x stronger would suffice.

**Comment by IsmollCheeKen** [comment]
I doubt +500% (1500% total) base bonus will make a difference, so I vouch for +1000% (2000% total) base bonus or higher, but should never be higher than the player's bonuses.

**Comment by PavelZinchenko** [comment]
Added skills to increase attack and defense of all mercenaries up to +200%
total attack/defense multiplier = (1 + skill bonus) * (1 + captain perks) * (1 + captain level*0.05 + ship level*0.05)
max value = (1 + 2)*(1 + 0.5 + 0.3)*(1 + 5 + 5) = x5.940
max value for player = x6.6
